//============================================================================
//  imdct_256_tb.sv — standalone unit test for the imdct_512 SHORT path (M16).
//
//  Identical harness to imdct_512_tb.sv but drives blksw=1 on the two test
//  channels so the DUT takes the 256-pt short transform, and checks every Q8.23
//  output sample against imdct256_golden.mem (liba52's a52_imdct_256 output
//  requantized to Q8.23).  Like the long path this is a fixed-point stage, so
//  the check is **bounded error**: the TB reports the max abs error in Q8.23 LSB
//  and fails only past TOL_LSB.  Generated by gen_imdct256_vec.c; driven by
//  bench/ac3/run_imdct256.sh.
//============================================================================
`timescale 1ns/1ps

module imdct_256_tb;
    logic clk = 0;
    always #5 clk = ~clk;
    logic rst;

    // Two blocks worth of coeffs/goldens: [0..511]=block0, [512..1023]=block1.
    logic signed [23:0] coeff_all [0:1023];
    logic signed [31:0] golden    [0:1023];
    // The active block's coeffs are mirrored here (the DUT addresses {ch,idx}<512).
    logic signed [23:0] coeff_src [0:511];

    logic [10:0] coeff_rd_addr;
    logic signed [23:0] coeff_rd_data;
    // 1-cycle synchronous read latency, matching mantissa_dequant.coeff_mem (M13).
    always_ff @(posedge clk) coeff_rd_data <= coeff_src[coeff_rd_addr[8:0]];

    logic [10:0] pcm_rd_addr;
    logic signed [31:0] pcm_rd_data;
    logic        start, done;

    // nfchans=2 → no downmix; blksw=all-ones → both channels take the short path.
    imdct_512 dut (
        .clk(clk), .rst(rst),
        .start(start),
        // dynrng: UNITY is 8'h00 under the correct (M17) two's-complement
        // exponent decode (8'h80 was the pre-M17 unity — see imdct_512_tb).
        .nfchans(3'd2), .blksw(5'b11111), .dynrng(8'h00), .cmixlev(2'd0), .surmixlev(2'd0),
        .coeff_rd_addr(coeff_rd_addr), .coeff_rd_data(coeff_rd_data),
        .pcm_rd_addr(pcm_rd_addr), .pcm_rd_data(pcm_rd_data),
        .done(done)
    );

    // Same tolerance basis as the long path (full-scale torture vector, peak
    // |sample| ~ 13).  3000 LSB leaves head-room; real content errs far less.
    localparam integer TOL_LSB = 3000;

    integer k, errs, maxerr, e, timeout, blk;
    initial begin
        $readmemh("imdct256_coeff.mem",  coeff_all);
        $readmemh("imdct256_golden.mem", golden);

        rst = 1; start = 0; pcm_rd_addr = 0;
        repeat (4) @(posedge clk);
        rst = 0;
        @(posedge clk);

        errs = 0; maxerr = 0;
        // Two consecutive blocks WITHOUT reset between them: block 0 writes the
        // overlap (first_blk path), block 1 reads it back — proving the short
        // delay-line packing of S_POST256, not just a fresh-delay single block.
        for (blk = 0; blk < 2; blk = blk + 1) begin
            for (k = 0; k < 512; k = k + 1) coeff_src[k] = coeff_all[blk*512 + k];

            start = 1; @(posedge clk); start = 0;
            timeout = 0;
            while (!done && timeout < 200000) begin @(posedge clk); timeout = timeout + 1; end
            if (!done) begin $display("FAIL: imdct_512 (short) never asserted done (blk %0d)", blk); $fatal; end

            for (k = 0; k < 512; k = k + 1) begin
                pcm_rd_addr = k[10:0];
                #1;
                e = pcm_rd_data - golden[blk*512 + k];
                if (e < 0) e = -e;
                if (e > maxerr) maxerr = e;
                if (e > TOL_LSB) begin
                    errs = errs + 1;
                    if (errs <= 10)
                        $display("  mismatch blk%0d [%0d] ch%0d idx%0d: dut=%0d golden=%0d (err=%0d LSB)",
                                 blk, k, k[8], k[7:0], pcm_rd_data, golden[blk*512 + k], e);
                end
            end
            @(posedge clk);
        end

        $display("imdct_256: max abs error = %0d Q8.23 LSB (~%e), tol = %0d (2 blocks, carried delay)",
                 maxerr, maxerr / 8388608.0, TOL_LSB);
        if (errs == 0) $display("PASS: imdct_512 short path within tolerance (1024 samples, 2 blocks)");
        else begin
            $display("FAIL: %0d sample(s) exceeded tolerance", errs);
            $fatal(1);   // nonzero exit — a plain $finish let run scripts read FAIL as pass
        end
        $finish;
    end
endmodule
