//============================================================================
//  mp2_decode.sv — fabric MPEG-1 Layer II (MP2) audio decoder.
//
//  The third playable codec in dvd_audio_decode (T_MP2 = 2'd3), covering the
//  DVD-spec "MPEG audio" format (stream_id 0xC0+n): pure-HDL serialized FSM in
//  the dvd/ac3 house style — no soft CPU (see docs/vcd_svcd_mpeg_reuse.md), all
//  tables/buffers in sync-read RAM (the recurring LUT-RAM lesson), serialized
//  multiplies (audio has ~600x cycle headroom at 27 MHz).
//
//  Scope: MPEG-1 (ID=1) Layer II, 32/44.1/48 kHz, all bitrates, mono / stereo /
//  dual / joint (intensity) stereo, stereo s16 out. No CRC check (CRC bytes
//  skipped). MPEG-2 LSF, Layer I/III -> never sync (15-bit qualified hunt);
//  free format / invalid header after sync -> err_unsupported (sticky; the
//  dvd_audio_decode self-heal watchdog wraps recovery). Output rate is the
//  core's fixed 48 kHz aud_ce; 44.1 kHz streams (future VCD) decode correctly
//  but play fast against it.
//
//  BIT-EXACT contract with tools/mp2_ref.py (the golden model — see its header
//  for the fixed-point derivation; bench/dvd/mp2_decode_tb.sv compares PCM
//  word-for-word against `mp2_ref.py fixture` output):
//    dequant   s2 = ((x <<< (25-nb)) + (1 << (24-dsh))) * C_q16 >>> 16   Q2.24
//    scale     S  = sat27(s2 * SCF_q20 >>> 20)
//    matrix    V[i] = sat32((sum_k N_q14[i][k] * S[k]) >>> 14)
//    window    pcm = sat16((sum_16taps D_q16 * V + 2^24) >>> 25)
//  ROMs generated by tools/gen_mp2_tables.py from the model's own tables.
//
//  Interface contract (dvd_audio_decode third-decoder shape, cf lpcm_unpack /
//  ac3_front+pcm_out): byte in + full backpressure; aud_ce (= aud_ce_play)
//  pops one stereo pair; audio_l/r are HELD between ticks; aud_valid pulses
//  the cycle after an aud_ce that popped a real pair. PCM-FIFO drain metering:
//  the FSM stalls before each 32-sample synthesis slot until the FIFO has
//  room, pacing the whole parser to the output rate (the ac3 pcm_out lesson).
//
//  Frame walk: after granule 12 the FSM skips to sync_bitpos + frame_len*8
//  (ancillary data), so an in-ancillary 0xFFFx pattern can't false-sync.
//
//  Mono note: the golden model runs the synthesis filterbank on a duplicated
//  channel 1; with identical inputs and identical (zero) initial state that is
//  bit-identical to duplicating channel 0's PCM, which is what we do (half the
//  synthesis work, same output).
//============================================================================

`timescale 1ns/1ps

module mp2_decode #(
    parameter int PCM_AW = 12          // PCM FIFO = 2^PCM_AW stereo pairs (~85 ms @48k)
) (
    input  logic        clk,
    input  logic        rst,           // synchronous, active-high

    input  logic        wr_en,
    input  logic [7:0]  wr_data,
    output logic        full,

    input  logic        aud_ce,        // ~48 kHz pop enable (aud_ce_play)
    output logic signed [15:0] audio_l,
    output logic signed [15:0] audio_r,
    output logic        aud_valid,

    output logic        synced,
    output logic        err_unsupported
);

    // ------------------------------------------------------------------
    // Input FIFO + bit reader (shared periphery from dvd/ac3)
    // ------------------------------------------------------------------
    logic [7:0]  bf_dout;
    logic        bf_empty, bf_rd;

    bit_fifo #(.DW(8), .DEPTH(4096)) u_bfifo (
        .clk(clk), .rst(rst),
        .wr_en(wr_en), .wr_data(wr_data), .full(full),
        .rd_data(bf_dout), .empty(bf_empty), .rd_en(bf_rd)
    );

    logic        br_req, br_ack;
    logic [5:0]  br_nbits;
    logic [15:0] br_data;
    logic [31:0] br_bitpos;

    bit_reader #(.MAXW(16)) u_brd (
        .clk(clk), .rst(rst),
        .fifo_dout(bf_dout), .fifo_empty(bf_empty), .fifo_rd(bf_rd),
        .req(br_req), .nbits(br_nbits), .ack(br_ack),
        .data(br_data), .bitpos(br_bitpos)
    );

    // ------------------------------------------------------------------
    // Quantization classes (index 0..16; 5'd31 = not allocated).
    // Constants pinned by tools/mp2_ref.py (C_Q16 / D_SHIFT / sample_bits).
    // ------------------------------------------------------------------
    localparam logic [4:0] CLS_NONE = 5'd31;

    function automatic [17:0] cls_c (input [4:0] c);
        case (c)
            5'd0:  cls_c = 18'h15555;  5'd1:  cls_c = 18'h1999a;
            5'd2:  cls_c = 18'h12492;  5'd3:  cls_c = 18'h1c71c;
            5'd4:  cls_c = 18'h11111;  5'd5:  cls_c = 18'h10842;
            5'd6:  cls_c = 18'h10410;  5'd7:  cls_c = 18'h10204;
            5'd8:  cls_c = 18'h10101;  5'd9:  cls_c = 18'h10080;
            5'd10: cls_c = 18'h10040;  5'd11: cls_c = 18'h10020;
            5'd12: cls_c = 18'h10010;  5'd13: cls_c = 18'h10008;
            5'd14: cls_c = 18'h10004;  5'd15: cls_c = 18'h10002;
            default: cls_c = 18'h10001;
        endcase
    endfunction

    function automatic [3:0] cls_dsh (input [4:0] c);
        case (c)
            5'd0, 5'd1, 5'd3: cls_dsh = 4'd1;
            5'd2:             cls_dsh = 4'd2;
            default:          cls_dsh = 4'(c) - 4'd1;
        endcase
    endfunction

    function automatic [4:0] cls_nb (input [4:0] c);
        case (c)
            5'd0:       cls_nb = 5'd2;
            5'd1, 5'd2: cls_nb = 5'd3;
            5'd3, 5'd4: cls_nb = 5'd4;
            default:    cls_nb = c;
        endcase
    endfunction

    function automatic cls_grouped (input [4:0] c);
        cls_grouped = (c == 5'd0) || (c == 5'd1) || (c == 5'd3);
    endfunction

    function automatic [3:0] cls_gbits (input [4:0] c);
        case (c)
            5'd0: cls_gbits = 4'd5;
            5'd1: cls_gbits = 4'd7;
            default: cls_gbits = 4'd10;
        endcase
    endfunction

    function automatic [3:0] cls_div (input [4:0] c);
        case (c)
            5'd0: cls_div = 4'd3;
            5'd1: cls_div = 4'd5;
            default: cls_div = 4'd9;
        endcase
    endfunction

    // Allocation-code -> class index (ISO Tables 3-B.2a-d; see mp2_ref).
    function automatic [4:0] qclass (input variant_cd, input [4:0] sb, input [3:0] code);
        if (code == 4'd0) qclass = CLS_NONE;
        else if (variant_cd) begin
            case (code)
                4'd1: qclass = 5'd0;
                4'd2: qclass = 5'd1;
                default: qclass = {1'b0, code};              // 3..15
            endcase
        end else begin
            if (sb < 5'd3) begin
                case (code)
                    4'd1: qclass = 5'd0;
                    4'd2: qclass = 5'd2;
                    default: qclass = {1'b0, code} + 5'd1;   // 3..15 -> 4..16
                endcase
            end else if (sb < 5'd23) begin
                // subbands 3..10 (nbal 4) and 11..22 (nbal 3) share the map:
                // code 1..14 -> class 0..13, top code -> 65535 (class 16)
                if ((sb < 5'd11 && code == 4'd15) || (sb >= 5'd11 && code == 4'd7))
                    qclass = 5'd16;
                else
                    qclass = {1'b0, code} - 5'd1;
            end else begin
                case (code)
                    4'd1: qclass = 5'd0;
                    4'd2: qclass = 5'd1;
                    default: qclass = 5'd16;
                endcase
            end
        end
    endfunction

    function automatic [2:0] nbal_of (input variant_cd, input [4:0] sb);
        if (variant_cd) nbal_of = (sb < 5'd2)  ? 3'd4 : 3'd3;
        else            nbal_of = (sb < 5'd11) ? 3'd4 : (sb < 5'd23) ? 3'd3 : 3'd2;
    endfunction

    // Layer II frame length in bytes (mirror of mp2_reframer.l2_bytes).
    function automatic [12:0] l2_bytes (input [1:0] fs, input [3:0] bidx);
        case ({fs, bidx})
            {2'b00, 4'd1}:  l2_bytes = 13'd104;   {2'b00, 4'd2}:  l2_bytes = 13'd156;
            {2'b00, 4'd3}:  l2_bytes = 13'd182;   {2'b00, 4'd4}:  l2_bytes = 13'd208;
            {2'b00, 4'd5}:  l2_bytes = 13'd261;   {2'b00, 4'd6}:  l2_bytes = 13'd313;
            {2'b00, 4'd7}:  l2_bytes = 13'd365;   {2'b00, 4'd8}:  l2_bytes = 13'd417;
            {2'b00, 4'd9}:  l2_bytes = 13'd522;   {2'b00, 4'd10}: l2_bytes = 13'd626;
            {2'b00, 4'd11}: l2_bytes = 13'd731;   {2'b00, 4'd12}: l2_bytes = 13'd835;
            {2'b00, 4'd13}: l2_bytes = 13'd1044;  {2'b00, 4'd14}: l2_bytes = 13'd1253;
            {2'b01, 4'd1}:  l2_bytes = 13'd96;    {2'b01, 4'd2}:  l2_bytes = 13'd144;
            {2'b01, 4'd3}:  l2_bytes = 13'd168;   {2'b01, 4'd4}:  l2_bytes = 13'd192;
            {2'b01, 4'd5}:  l2_bytes = 13'd240;   {2'b01, 4'd6}:  l2_bytes = 13'd288;
            {2'b01, 4'd7}:  l2_bytes = 13'd336;   {2'b01, 4'd8}:  l2_bytes = 13'd384;
            {2'b01, 4'd9}:  l2_bytes = 13'd480;   {2'b01, 4'd10}: l2_bytes = 13'd576;
            {2'b01, 4'd11}: l2_bytes = 13'd672;   {2'b01, 4'd12}: l2_bytes = 13'd768;
            {2'b01, 4'd13}: l2_bytes = 13'd960;   {2'b01, 4'd14}: l2_bytes = 13'd1152;
            {2'b10, 4'd1}:  l2_bytes = 13'd144;   {2'b10, 4'd2}:  l2_bytes = 13'd216;
            {2'b10, 4'd3}:  l2_bytes = 13'd252;   {2'b10, 4'd4}:  l2_bytes = 13'd288;
            {2'b10, 4'd5}:  l2_bytes = 13'd360;   {2'b10, 4'd6}:  l2_bytes = 13'd432;
            {2'b10, 4'd7}:  l2_bytes = 13'd504;   {2'b10, 4'd8}:  l2_bytes = 13'd576;
            {2'b10, 4'd9}:  l2_bytes = 13'd720;   {2'b10, 4'd10}: l2_bytes = 13'd864;
            {2'b10, 4'd11}: l2_bytes = 13'd1008;  {2'b10, 4'd12}: l2_bytes = 13'd1152;
            {2'b10, 4'd13}: l2_bytes = 13'd1440;  {2'b10, 4'd14}: l2_bytes = 13'd1728;
            default:        l2_bytes = 13'd0;
        endcase
    endfunction

    // ------------------------------------------------------------------
    // ROMs (generated: tools/gen_mp2_tables.py)
    // ------------------------------------------------------------------
    logic signed [15:0] n_rom [0:2047];     // N[i][k] Q1.14, addr {i[5:0],k[4:0]}
    logic signed [17:0] d_rom [0:511];      // D[j] Q2.16
    logic        [21:0] scf_rom [0:63];     // 2*2^(-i/3) Q1.20 (idx 63 = 0)
    initial $readmemh("dvd/mp2/mp2_nrom.mem",   n_rom);
    initial $readmemh("dvd/mp2/mp2_drom.mem",   d_rom);
    initial $readmemh("dvd/mp2/mp2_scfrom.mem", scf_rom);

    logic [10:0] nrom_ra;   logic signed [15:0] nrom_rd;
    logic [8:0]  drom_ra;   logic signed [17:0] drom_rd;
    logic [5:0]  scfrom_ra; logic        [21:0] scfrom_rd;
    always_ff @(posedge clk) begin
        nrom_rd   <= n_rom[nrom_ra];
        drom_rd   <= d_rom[drom_ra];
        scfrom_rd <= scf_rom[scfrom_ra];
    end

    // ------------------------------------------------------------------
    // Working memories (all sync-read, registered outputs)
    // ------------------------------------------------------------------
    logic [4:0] alloc_ram [0:63];           // class index per {ch, sb}
    logic [5:0] alloc_wa, alloc_ra;
    logic [4:0] alloc_wd, alloc_rd;
    logic       alloc_we;
    always_ff @(posedge clk) begin
        if (alloc_we) alloc_ram[alloc_wa] <= alloc_wd;
        alloc_rd <= alloc_ram[alloc_ra];
    end

    logic [1:0] scfsi_ram [0:63];           // per {ch, sb}
    logic [5:0] scfsi_wa, scfsi_ra;
    logic [1:0] scfsi_wd, scfsi_rd;
    logic       scfsi_we;
    always_ff @(posedge clk) begin
        if (scfsi_we) scfsi_ram[scfsi_wa] <= scfsi_wd;
        scfsi_rd <= scfsi_ram[scfsi_ra];
    end

    logic [5:0] scf_ram [0:255];            // scf index per {part[1:0], ch, sb}
    logic [7:0] scf_wa, scf_ra;
    logic [5:0] scf_wd, scf_rd;
    logic       scf_we;
    always_ff @(posedge clk) begin
        if (scf_we) scf_ram[scf_wa] <= scf_wd;
        scf_rd <= scf_ram[scf_ra];
    end

    logic signed [26:0] s_mem [0:255];      // Q2.24 samples per {k[1:0], ch, sb}
    logic [7:0]  smem_wa, smem_ra;
    logic signed [26:0] smem_wd, smem_rd;
    logic        smem_we;
    always_ff @(posedge clk) begin
        if (smem_we) s_mem[smem_wa] <= smem_wd;
        smem_rd <= s_mem[smem_ra];
    end

    logic signed [31:0] v_mem [0:2047];     // V ring, 1024 per channel {ch, va}
    logic [10:0] vmem_wa, vmem_ra;
    logic signed [31:0] vmem_wd, vmem_rd;
    logic        vmem_we;
    always_ff @(posedge clk) begin
        if (vmem_we) v_mem[vmem_wa] <= vmem_wd;
        vmem_rd <= v_mem[vmem_ra];
    end

    logic signed [15:0] lbuf [0:31];        // channel-0 PCM staging for pairing
    logic [4:0]  lbuf_wa, lbuf_ra;
    logic signed [15:0] lbuf_wd, lbuf_rd;
    logic        lbuf_we;
    always_ff @(posedge clk) begin
        if (lbuf_we) lbuf[lbuf_wa] <= lbuf_wd;
        lbuf_rd <= lbuf[lbuf_ra];
    end

    // ------------------------------------------------------------------
    // PCM FIFO ({r[15:0], l[15:0]}) with fill count for slot metering
    // ------------------------------------------------------------------
    localparam int PCM_DEPTH = 1 << PCM_AW;
    logic [31:0] pcm_mem [0:PCM_DEPTH-1];
    logic [PCM_AW-1:0] pcm_wp, pcm_rp;
    logic [PCM_AW:0]   pcm_cnt;
    logic        pcm_push;
    logic [31:0] pcm_wdata;
    logic [31:0] pcm_head;
    logic        head_ok;               // delayed non-empty: guards the
                                        // registered-head read-during-write race
    wire [PCM_AW:0] pcm_free = (PCM_AW+1)'(PCM_DEPTH) - pcm_cnt;
    wire pcm_pop = aud_ce && head_ok;

    always_ff @(posedge clk) begin
        if (rst) begin
            pcm_wp <= '0; pcm_rp <= '0; pcm_cnt <= '0; head_ok <= 1'b0;
        end else begin
            head_ok <= (pcm_cnt != '0);
            if (pcm_push) begin
                pcm_mem[pcm_wp] <= pcm_wdata;
                pcm_wp <= pcm_wp + 1'b1;
            end
            if (pcm_pop) pcm_rp <= pcm_rp + 1'b1;
            case ({pcm_push, pcm_pop})
                2'b10: pcm_cnt <= pcm_cnt + 1'b1;
                2'b01: pcm_cnt <= pcm_cnt - 1'b1;
                default: ;
            endcase
        end
    end
    always_ff @(posedge clk) pcm_head <= pcm_mem[pcm_rp];

    always_ff @(posedge clk) begin
        if (rst) begin
            audio_l <= '0; audio_r <= '0; aud_valid <= 1'b0;
        end else begin
            aud_valid <= pcm_pop;
            if (pcm_pop) begin
                audio_l <= pcm_head[15:0];
                audio_r <= pcm_head[31:16];
            end
        end
    end

    // ------------------------------------------------------------------
    // Saturation helpers (match mp2_ref.sat exactly).
    // ⚠ The min-clamp RESULTS are written as HEX BIT PATTERNS, not negated
    // decimals: `-27'sd67108864` overflows the signed-27 literal (max is
    // 2^26-1) — Icarus wraps it to the intended pattern (sim was bit-exact)
    // but Quartus 17 raises "Warning (10259): constant value overflow" and
    // mangles the clamp → the first HW build played SILENCE. Same for
    // 32'sd2147483648 and 16'sd32768. The comparison-side literals are
    // wide enough and fine.
    // ------------------------------------------------------------------
    function automatic signed [26:0] sat27 (input signed [48:0] v);
        if      (v >  49'sd67108863)  sat27 = 27'sd67108863;
        else if (v < -49'sd67108864)  sat27 = 27'sh4000000;    // -2^26
        else                          sat27 = 27'(v);
    endfunction

    function automatic signed [31:0] sat32 (input signed [47:0] v);
        if      (v >  48'sd2147483647)  sat32 = 32'sd2147483647;
        else if (v < -48'sd2147483648)  sat32 = 32'sh80000000;  // -2^31
        else                            sat32 = 32'(v);
    endfunction

    function automatic signed [15:0] sat16 (input signed [53:0] v);
        if      (v >  54'sd32767)  sat16 = 16'sd32767;
        else if (v < -54'sd32768)  sat16 = 16'sh8000;           // -32768
        else                       sat16 = 16'(v);
    endfunction

    // requantizer seed: ((code ^ msb) sign-extended) <<< (25-nb), plus D.
    function automatic signed [25:0] dq_seed (input [16:0] code, input [4:0] nb,
                                              input [3:0] dsh);
        logic [16:0] x;
        logic signed [16:0] xs;
        logic signed [25:0] xq;
        begin
            x = code ^ (17'd1 << (nb - 5'd1));
            if (x[nb-5'd1]) xs = signed'(x | ~((17'd1 << nb) - 17'd1));
            else            xs = signed'(x &  ((17'd1 << nb) - 17'd1));
            xq = 26'(xs) <<< (5'd25 - nb);
            dq_seed = xq + (26'sd1 <<< (5'd24 - {1'b0, dsh}));
        end
    endfunction

    // ------------------------------------------------------------------
    // FSM
    // ------------------------------------------------------------------
    typedef enum logic [5:0] {
        ST_INIT,
        ST_HUNT0, ST_HUNT0W, ST_HUNT1, ST_HUNT1W,
        ST_HDR, ST_HDRW, ST_CRC, ST_CRCW,
        ST_AL_REQ, ST_AL_ACK,
        ST_SI_RD, ST_SI_RD2, ST_SI_CHK, ST_SI_ACK, ST_SI_ADV,
        ST_SF_RD, ST_SF_RD2, ST_SF_CHK, ST_SF_REQ, ST_SF_ACK, ST_SF_WR2, ST_SF_ADV,
        ST_SMP_RD, ST_SMP_RD2, ST_SMP_CHK,
        ST_SMP_GREQ, ST_SMP_GACK, ST_DIV, ST_SMP_UREQ, ST_SMP_UACK,
        ST_SMP_ZERO,
        ST_DQ_SCF, ST_DQ_SCFW, ST_DQ_SCF2, ST_DQ_M1, ST_DQ_M2, ST_DQ_WR, ST_SMP_ADV,
        ST_SYN_WAIT, ST_SYN_VOFF,
        ST_MAT_RUN, ST_MAT_VWR,
        ST_WIN_RUN, ST_WIN_OUT,
        ST_SYN_NEXT,
        ST_SKIP, ST_SKIPW
    } st_e;

    st_e st;

    // header context
    logic        prot_nocrc;
    logic [3:0]  bidx;
    logic [1:0]  fs, mode, mode_ext;
    logic        padbit;
    logic        variant_cd;
    logic [4:0]  sblimit, bound;
    logic        mono, nch2;
    logic [31:0] sync_bitpos;
    logic [13:0] frame_bytes;

    // loop counters / context
    logic [10:0] init_cnt;
    logic [4:0]  sb;
    logic        ch;
    logic [3:0]  gran;
    logic [1:0]  part;
    logic [1:0]  k;                    // triplet sample index / synth slot
    logic [1:0]  sf_field, sf_cnt;
    logic        sf_p2_pending;
    logic [5:0]  wi, wk;
    logic [1:0]  zk;
    logic [4:0]  cls, saved_cls;
    logic        shared_sb;
    logic [16:0] s_raw [0:2];

    // divider
    logic [9:0]  div_n, div_q;
    logic [3:0]  div_r;
    logic [3:0]  div_cnt;
    logic        div_phase;
    logic [4:0]  racc;                 // comb temp (blocking)
    logic        racc_ge;

    // dequant datapath
    logic signed [25:0] dq_s;
    logic signed [43:0] dq_p1;
    logic signed [48:0] dq_p2;         // comb temp (blocking)
    logic [1:0]  dq_k;

    // synthesis
    logic [9:0]  voff [0:1];
    logic signed [47:0] mac;
    logic signed [53:0] wmac;
    logic [1:0]  pipe_v;
    logic signed [15:0] pcm_t;         // comb temp (blocking)
    logic [31:0] skip_target;          // comb temp (blocking)

    wire ch_top = nch2;
    wire shared_alloc_reuse = (sb >= bound) && ch;   // alloc walk: ch1 of a
                                                     // shared (intensity) subband
    wire [4:0] jbound = {mode_ext, 2'b00} + 5'd4;    // (mode_ext+1)*4, max 16

    always_ff @(posedge clk) begin
        if (rst) begin
            st <= ST_INIT;
            br_req <= 1'b0; br_nbits <= '0;
            alloc_we <= 1'b0; scfsi_we <= 1'b0; scf_we <= 1'b0;
            smem_we <= 1'b0; vmem_we <= 1'b0; lbuf_we <= 1'b0;
            pcm_push <= 1'b0; pcm_wdata <= '0;
            synced <= 1'b0; err_unsupported <= 1'b0;
            init_cnt <= '0;
            voff[0] <= '0; voff[1] <= '0;
            alloc_wa <= '0; alloc_ra <= '0; alloc_wd <= '0;
            scfsi_wa <= '0; scfsi_ra <= '0; scfsi_wd <= '0;
            scf_wa <= '0; scf_ra <= '0; scf_wd <= '0;
            smem_wa <= '0; smem_ra <= '0; smem_wd <= '0;
            vmem_wa <= '0; vmem_ra <= '0; vmem_wd <= '0;
            lbuf_wa <= '0; lbuf_ra <= '0; lbuf_wd <= '0;
            nrom_ra <= '0; drom_ra <= '0; scfrom_ra <= '0;
            sb <= '0; ch <= 1'b0; gran <= '0; part <= '0; k <= '0;
            sf_field <= '0; sf_cnt <= '0; sf_p2_pending <= 1'b0;
            wi <= '0; wk <= '0; zk <= '0;
            cls <= CLS_NONE; saved_cls <= CLS_NONE; shared_sb <= 1'b0;
            s_raw[0] <= '0; s_raw[1] <= '0; s_raw[2] <= '0;
            div_n <= '0; div_q <= '0; div_r <= '0; div_cnt <= '0; div_phase <= 1'b0;
            dq_s <= '0; dq_p1 <= '0; dq_k <= '0;
            mac <= '0; wmac <= '0; pipe_v <= '0;
            prot_nocrc <= 1'b0; bidx <= '0; fs <= '0; mode <= '0; mode_ext <= '0;
            padbit <= 1'b0; variant_cd <= 1'b0; sblimit <= '0; bound <= '0;
            mono <= 1'b0; nch2 <= 1'b0; sync_bitpos <= '0; frame_bytes <= '0;
        end else begin
            br_req <= 1'b0;
            alloc_we <= 1'b0; scfsi_we <= 1'b0; scf_we <= 1'b0;
            smem_we <= 1'b0; vmem_we <= 1'b0; lbuf_we <= 1'b0;
            pcm_push <= 1'b0;

            case (st)

            // ---- init: clear V ring; S entries above sblimit stay 0 forever
            ST_INIT: begin
                vmem_wa <= init_cnt; vmem_wd <= '0; vmem_we <= 1'b1;
                if (init_cnt < 11'd256) begin
                    smem_wa <= 8'(init_cnt); smem_wd <= '0; smem_we <= 1'b1;
                end
                init_cnt <= init_cnt + 1'b1;
                if (init_cnt == 11'd2047) st <= ST_HUNT0;
            end

            // ---- sync hunt: 0xFF then 1111_110x (sync + ID=MPEG-1 + layer=II)
            ST_HUNT0:  begin br_req <= 1'b1; br_nbits <= 6'd8; st <= ST_HUNT0W; end
            ST_HUNT0W: if (br_ack) begin
                if (br_data[7:0] == 8'hFF) st <= ST_HUNT1;
                else st <= ST_HUNT0;
            end
            ST_HUNT1:  begin br_req <= 1'b1; br_nbits <= 6'd8; st <= ST_HUNT1W; end
            ST_HUNT1W: if (br_ack) begin
                if (br_data[7:1] == 7'b1111_110) begin
                    prot_nocrc  <= br_data[0];
                    sync_bitpos <= br_bitpos - 32'd16;
                    st <= ST_HDR;
                end else if (br_data[7:0] == 8'hFF) st <= ST_HUNT1;
                else st <= ST_HUNT0;
            end

            // ---- header bytes 2..3
            ST_HDR:  begin br_req <= 1'b1; br_nbits <= 6'd16; st <= ST_HDRW; end
            ST_HDRW: if (br_ack) begin
                bidx     <= br_data[15:12];
                fs       <= br_data[11:10];
                padbit   <= br_data[9];
                mode     <= br_data[7:6];
                mode_ext <= br_data[5:4];
                if (br_data[15:12] == 4'd0 || br_data[15:12] == 4'd15
                    || br_data[11:10] == 2'b11) begin
                    if (synced) err_unsupported <= 1'b1;
                    st <= ST_HUNT0;
                end else begin
                    synced <= 1'b1;
                    frame_bytes <= {1'b0, l2_bytes(br_data[11:10], br_data[15:12])}
                                   + {13'd0, br_data[9]};
                    mono <= (br_data[7:6] == 2'b11);
                    nch2 <= (br_data[7:6] != 2'b11);
                    // table variant + sblimit (mirrors mp2_ref.table_select):
                    //   pc_lo: per-channel bitrate in {32,48} kbps
                    //   pc_hi: per-channel bitrate >= 96 kbps
                    if (br_data[7:6] == 2'b11
                        ? (br_data[15:12] == 4'd1 || br_data[15:12] == 4'd2)
                        : (br_data[15:12] == 4'd4 || br_data[15:12] == 4'd6)) begin
                        variant_cd <= 1'b1;
                        sblimit    <= (br_data[11:10] == 2'b10) ? 5'd12 : 5'd8;
                    end else if (br_data[11:10] == 2'b01) begin
                        variant_cd <= 1'b0; sblimit <= 5'd27;
                    end else if (br_data[7:6] == 2'b11
                        ? (br_data[15:12] >= 4'd6)
                        : (br_data[15:12] >= 4'd10)) begin
                        variant_cd <= 1'b0; sblimit <= 5'd30;
                    end else begin
                        variant_cd <= 1'b0; sblimit <= 5'd27;
                    end
                    sb <= '0; ch <= 1'b0;
                    if (prot_nocrc) st <= ST_AL_REQ;
                    else st <= ST_CRC;
                end
            end

            ST_CRC:  begin br_req <= 1'b1; br_nbits <= 6'd16; st <= ST_CRCW; end
            ST_CRCW: if (br_ack) begin sb <= '0; ch <= 1'b0; st <= ST_AL_REQ; end

            // ---- allocation walk (sb outer, ch inner; shared sb: ch1 no read)
            ST_AL_REQ: begin
                if (sb == 5'd0 && !ch)
                    bound <= (mode == 2'b01 && jbound < sblimit) ? jbound : sblimit;
                if (shared_alloc_reuse) begin
                    alloc_wa <= {1'b1, sb}; alloc_wd <= saved_cls; alloc_we <= 1'b1;
                    st <= ST_AL_ACK;
                end else begin
                    br_req <= 1'b1; br_nbits <= {3'd0, nbal_of(variant_cd, sb)};
                    st <= ST_AL_ACK;
                end
            end
            ST_AL_ACK: if (shared_alloc_reuse || br_ack) begin
                if (!shared_alloc_reuse) begin
                    alloc_wa <= {ch, sb};
                    alloc_wd <= qclass(variant_cd, sb, br_data[3:0]);
                    alloc_we <= 1'b1;
                    if (sb >= bound)
                        saved_cls <= qclass(variant_cd, sb, br_data[3:0]);
                end
                if (ch != ch_top) begin
                    ch <= 1'b1; st <= ST_AL_REQ;
                end else begin
                    ch <= 1'b0;
                    if (sb == sblimit - 5'd1) begin
                        sb <= '0; st <= ST_SI_RD;
                    end else begin
                        sb <= sb + 5'd1; st <= ST_AL_REQ;
                    end
                end
            end

            // ---- scfsi walk ----
            // sync-read timing: ra registers at the end of *_RD, the RAM output
            // register updates at the end of *_RD2, so *_CHK sees fresh data.
            ST_SI_RD:  begin alloc_ra <= {ch, sb}; st <= ST_SI_RD2; end
            ST_SI_RD2: st <= ST_SI_CHK;
            ST_SI_CHK: begin
                if (alloc_rd != CLS_NONE) begin
                    br_req <= 1'b1; br_nbits <= 6'd2; st <= ST_SI_ACK;
                end else st <= ST_SI_ADV;
            end
            ST_SI_ACK: if (br_ack) begin
                scfsi_wa <= {ch, sb}; scfsi_wd <= br_data[1:0]; scfsi_we <= 1'b1;
                st <= ST_SI_ADV;
            end
            ST_SI_ADV: begin
                if (ch != ch_top) begin
                    ch <= 1'b1; st <= ST_SI_RD;
                end else begin
                    ch <= 1'b0;
                    if (sb == sblimit - 5'd1) begin
                        sb <= '0; st <= ST_SF_RD;
                    end else begin
                        sb <= sb + 5'd1; st <= ST_SI_RD;
                    end
                end
            end

            // ---- scalefactor walk ----
            ST_SF_RD:  begin
                alloc_ra <= {ch, sb}; scfsi_ra <= {ch, sb};
                st <= ST_SF_RD2;
            end
            ST_SF_RD2: st <= ST_SF_CHK;
            ST_SF_CHK: begin
                if (alloc_rd != CLS_NONE) begin
                    sf_field <= 2'd0;
                    sf_p2_pending <= 1'b0;
                    case (scfsi_rd)
                        2'd0: sf_cnt <= 2'd3;
                        2'd2: sf_cnt <= 2'd1;
                        default: sf_cnt <= 2'd2;
                    endcase
                    st <= ST_SF_REQ;
                end else st <= ST_SF_ADV;
            end
            ST_SF_REQ: begin br_req <= 1'b1; br_nbits <= 6'd6; st <= ST_SF_ACK; end
            ST_SF_ACK: if (br_ack) begin
                // field -> part mapping per scfsi (matches mp2_ref):
                //   0: f0->p0, f1->p1, f2->p2
                //   1: f0->p0+p1, f1->p2
                //   2: f0->p0+p1+p2
                //   3: f0->p0, f1->p1+p2
                scf_wd <= br_data[5:0];
                scf_we <= 1'b1;
                case (scfsi_rd)
                    2'd0: scf_wa <= {sf_field, ch, sb};
                    2'd1: scf_wa <= (sf_field == 2'd0) ? {2'd0, ch, sb} : {2'd2, ch, sb};
                    2'd2: scf_wa <= {2'd0, ch, sb};
                    default: scf_wa <= (sf_field == 2'd0) ? {2'd0, ch, sb} : {2'd1, ch, sb};
                endcase
                st <= ST_SF_WR2;
            end
            ST_SF_WR2: begin
                // duplicate writes for the shared patterns; scf_wd still holds
                // the field value (only scf_wa/scf_we change here)
                if (sf_p2_pending) begin
                    scf_wa <= {2'd2, ch, sb}; scf_we <= 1'b1;
                    sf_p2_pending <= 1'b0;
                    if (sf_cnt == 2'd1) st <= ST_SF_ADV;
                    else begin
                        sf_cnt <= sf_cnt - 2'd1; sf_field <= sf_field + 2'd1;
                        st <= ST_SF_REQ;
                    end
                end else begin
                    case (scfsi_rd)
                        2'd1: if (sf_field == 2'd0) begin
                            scf_wa <= {2'd1, ch, sb}; scf_we <= 1'b1;
                        end
                        2'd2: begin
                            scf_wa <= {2'd1, ch, sb}; scf_we <= 1'b1;
                            sf_p2_pending <= 1'b1;
                        end
                        2'd3: if (sf_field == 2'd1) begin
                            scf_wa <= {2'd2, ch, sb}; scf_we <= 1'b1;
                        end
                        default: ;
                    endcase
                    if (scfsi_rd == 2'd2) begin
                        st <= ST_SF_WR2;      // p2 write next cycle
                    end else if (sf_cnt == 2'd1) begin
                        st <= ST_SF_ADV;
                    end else begin
                        sf_cnt <= sf_cnt - 2'd1; sf_field <= sf_field + 2'd1;
                        st <= ST_SF_REQ;
                    end
                end
            end
            ST_SF_ADV: begin
                if (ch != ch_top) begin
                    ch <= 1'b1; st <= ST_SF_RD;
                end else begin
                    ch <= 1'b0;
                    if (sb == sblimit - 5'd1) begin
                        // scalefactors done -> granule loop
                        gran <= '0; part <= '0; sb <= '0;
                        st <= ST_SMP_RD;
                    end else begin
                        sb <= sb + 5'd1; st <= ST_SF_RD;
                    end
                end
            end

            // ---- granule sample walk ----
            ST_SMP_RD: begin
                shared_sb <= (sb >= bound);
                alloc_ra  <= {ch, sb};
                st <= ST_SMP_RD2;
            end
            ST_SMP_RD2: st <= ST_SMP_CHK;
            ST_SMP_CHK: begin
                cls <= alloc_rd;
                if (alloc_rd == CLS_NONE) begin
                    zk <= 2'd0; st <= ST_SMP_ZERO;
                end else if (shared_sb && ch) begin
                    dq_k <= 2'd0; st <= ST_DQ_SCF;   // reuse ch0's s_raw
                end else if (cls_grouped(alloc_rd)) begin
                    st <= ST_SMP_GREQ;
                end else begin
                    k <= 2'd0; st <= ST_SMP_UREQ;
                end
            end
            ST_SMP_ZERO: begin
                smem_wa <= {zk, ch, sb}; smem_wd <= '0; smem_we <= 1'b1;
                if (zk == 2'd2) st <= ST_SMP_ADV;
                else zk <= zk + 2'd1;
            end
            ST_SMP_GREQ: begin
                br_req <= 1'b1; br_nbits <= {2'd0, cls_gbits(cls)};
                st <= ST_SMP_GACK;
            end
            ST_SMP_GACK: if (br_ack) begin
                div_n <= br_data[9:0]; div_q <= '0; div_r <= '0;
                div_cnt <= 4'd9; div_phase <= 1'b0;
                st <= ST_DIV;
            end
            ST_DIV: begin
                racc    = {div_r, div_n[div_cnt]};
                racc_ge = (racc >= {1'b0, cls_div(cls)});
                div_r <= racc_ge ? 4'(racc - {1'b0, cls_div(cls)}) : racc[3:0];
                div_q <= {div_q[8:0], racc_ge};
                if (div_cnt == 4'd0) begin
                    if (!div_phase) begin
                        s_raw[0] <= {13'd0, racc_ge ? 4'(racc - {1'b0, cls_div(cls)})
                                                    : racc[3:0]};
                        div_n <= {div_q[8:0], racc_ge};
                        div_q <= '0; div_r <= '0; div_cnt <= 4'd9;
                        div_phase <= 1'b1;
                    end else begin
                        s_raw[1] <= {13'd0, racc_ge ? 4'(racc - {1'b0, cls_div(cls)})
                                                    : racc[3:0]};
                        s_raw[2] <= {7'd0, div_q[8:0], racc_ge};
                        dq_k <= 2'd0; st <= ST_DQ_SCF;
                    end
                end else div_cnt <= div_cnt - 4'd1;
            end
            ST_SMP_UREQ: begin
                br_req <= 1'b1; br_nbits <= 6'(cls_nb(cls));
                st <= ST_SMP_UACK;
            end
            ST_SMP_UACK: if (br_ack) begin
                s_raw[k] <= {1'b0, br_data};
                if (k == 2'd2) begin dq_k <= 2'd0; st <= ST_DQ_SCF; end
                else begin k <= k + 2'd1; st <= ST_SMP_UREQ; end
            end

            // ---- dequantize the 3 samples of (ch, sb) ----
            ST_DQ_SCF:  begin scf_ra <= {part, ch, sb}; st <= ST_DQ_SCFW; end
            ST_DQ_SCFW: st <= ST_DQ_SCF2;               // scf_rd settling
            ST_DQ_SCF2: begin scfrom_ra <= scf_rd;      st <= ST_DQ_M1;   end
            ST_DQ_M1: begin
                dq_s <= dq_seed(s_raw[dq_k], cls_nb(cls), cls_dsh(cls));
                st <= ST_DQ_M2;
            end
            ST_DQ_M2: begin
                dq_p1 <= dq_s * signed'({1'b0, cls_c(cls)});
                st <= ST_DQ_WR;
            end
            ST_DQ_WR: begin
                dq_p2 = signed'(27'(dq_p1 >>> 16)) * signed'({1'b0, scfrom_rd});
                smem_wa <= {dq_k, ch, sb};
                smem_wd <= sat27(dq_p2 >>> 20);
                smem_we <= 1'b1;
                if (dq_k == 2'd2) st <= ST_SMP_ADV;
                else begin dq_k <= dq_k + 2'd1; st <= ST_DQ_M1; end
            end
            ST_SMP_ADV: begin
                if (ch != ch_top) begin
                    ch <= 1'b1; st <= ST_SMP_RD;
                end else begin
                    ch <= 1'b0;
                    if (sb == sblimit - 5'd1) begin
                        // granule parsed -> synthesize slots k = 0..2
                        sb <= '0; k <= 2'd0;
                        st <= ST_SYN_WAIT;
                    end else begin
                        sb <= sb + 5'd1; st <= ST_SMP_RD;
                    end
                end
            end

            // ---- synthesis: one 32-sample slot per channel ----
            ST_SYN_WAIT: begin
                if (pcm_free >= (PCM_AW+1)'(32)) begin
                    ch <= 1'b0;
                    st <= ST_SYN_VOFF;
                end
            end
            ST_SYN_VOFF: begin
                voff[ch] <= voff[ch] - 10'd64;
                wi <= '0; wk <= '0; mac <= '0; pipe_v <= '0;
                st <= ST_MAT_RUN;
            end
            ST_MAT_RUN: begin
                if (wk < 6'd32) begin
                    nrom_ra <= {wi, wk[4:0]};
                    smem_ra <= {k, ch, wk[4:0]};
                end
                pipe_v <= {pipe_v[0], (wk < 6'd32)};
                if (pipe_v[1])
                    mac <= mac + 48'(nrom_rd * smem_rd);
                if (wk == 6'd34) st <= ST_MAT_VWR;
                else wk <= wk + 6'd1;
            end
            ST_MAT_VWR: begin
                vmem_wa <= {ch, voff[ch] + {4'd0, wi}};
                vmem_wd <= sat32(mac >>> 14);
                vmem_we <= 1'b1;
                mac <= '0; wk <= '0; pipe_v <= '0;
                if (wi == 6'd63) begin
                    wi <= '0; wmac <= '0;
                    st <= ST_WIN_RUN;
                end else begin
                    wi <= wi + 6'd1;
                    st <= ST_MAT_RUN;
                end
            end
            ST_WIN_RUN: begin
                // window j = wi[4:0], taps t = 0..15 (wk), 2-cycle read pipeline:
                //  even t: D[j + 64*(t/2)],      V[voff + j + 128*(t/2)]
                //  odd  t: D[j + 64*(t/2) + 32], V[voff + j + 128*(t/2) + 96]
                if (wk < 6'd16) begin
                    drom_ra <= {wk[3:1], 6'd0} + {4'd0, wi[4:0]}
                               + (wk[0] ? 9'd32 : 9'd0);
                    vmem_ra <= {ch, voff[ch] + {5'd0, wi[4:0]}
                                    + {wk[3:1], 7'd0}
                                    + (wk[0] ? 10'd96 : 10'd0)};
                end
                pipe_v <= {pipe_v[0], (wk < 6'd16)};
                if (pipe_v[1])
                    wmac <= wmac + 54'(drom_rd * vmem_rd);
                if (wk == 6'd18) st <= ST_WIN_OUT;
                else wk <= wk + 6'd1;
            end
            ST_WIN_OUT: begin
                pcm_t = sat16((wmac + 54'sd16777216) >>> 25);
                if (!ch) begin
                    lbuf_wa <= wi[4:0]; lbuf_wd <= pcm_t; lbuf_we <= 1'b1;
                    if (mono) begin
                        pcm_wdata <= {pcm_t, pcm_t}; pcm_push <= 1'b1;
                    end
                end else begin
                    pcm_wdata <= {pcm_t, lbuf_rd}; pcm_push <= 1'b1;
                    lbuf_ra <= wi[4:0] + 5'd1;        // next pair's L
                end
                wmac <= '0; wk <= '0; pipe_v <= '0;
                if (wi[4:0] == 5'd31) st <= ST_SYN_NEXT;
                else begin
                    wi <= wi + 6'd1;
                    st <= ST_WIN_RUN;
                end
            end
            ST_SYN_NEXT: begin
                if (!ch && !mono) begin
                    ch <= 1'b1;
                    st <= ST_SYN_VOFF;
                end else begin
                    ch <= 1'b0;
                    if (k == 2'd2) begin
                        k <= 2'd0;
                        if (gran == 4'd11) st <= ST_SKIP;
                        else begin
                            gran <= gran + 4'd1;
                            part <= (gran >= 4'd7) ? 2'd2 : (gran >= 4'd3) ? 2'd1 : 2'd0;
                            sb <= '0; st <= ST_SMP_RD;
                        end
                    end else begin
                        k <= k + 2'd1;
                        st <= ST_SYN_WAIT;
                    end
                end
            end

            // ---- skip ancillary data to the frame boundary ----
            ST_SKIP: begin
                skip_target = sync_bitpos + {15'd0, frame_bytes, 3'd0};   // *8
                if (br_bitpos >= skip_target) begin
                    if (br_bitpos > skip_target) err_unsupported <= 1'b1;
                    st <= ST_HUNT0;
                end else begin
                    br_req <= 1'b1;
                    br_nbits <= (skip_target - br_bitpos >= 32'd16)
                                ? 6'd16 : 6'(skip_target - br_bitpos);
                    st <= ST_SKIPW;
                end
            end
            ST_SKIPW: if (br_ack) st <= ST_SKIP;

            default: st <= ST_HUNT0;
            endcase
        end
    end

endmodule
