#!/usr/bin/env python3
"""Generate bench/dvd/test_vobs/aud_map_vec.hex — golden vectors for
bench/dvd/aud_stream_map_tb.sv, from the reference model
tools/dvd_vm_ref.py aud_stream_map() (the libdvdnav vm_get_audio_stream port).

Vector format, one hex word per line, 40 bits:
  [39:37] expect (phys_streamN)
  [36:13] phys_flat  {phys7..phys0}
  [12:5]  avail
  [4:2]   logical
  [1]     dom_tt
  [0]     map_valid

Deterministic (seeded) — regenerating always produces the same file.
"""
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dvd_vm_ref import aud_stream_map


def table(avail, phys):
    """Build audio_ctl words from avail bits + phys list."""
    return [((avail >> n & 1) << 15) | ((phys[n] & 7) << 8) for n in range(8)]


def vec(map_valid, dom_tt, logical, avail, phys):
    ctl = table(avail, phys)
    exp = aud_stream_map(logical, ctl, dom_tt, map_valid=map_valid)
    flat = 0
    for n in range(8):
        flat |= (phys[n] & 7) << (3 * n)
    return ((exp & 7) << 37) | (flat << 13) | ((avail & 0xFF) << 5) \
           | ((logical & 7) << 2) | (int(dom_tt) << 1) | int(map_valid)


def main():
    out = []
    ident = list(range(8))
    getsmart = [3, 3, 3, 0, 0, 0, 0, 0]        # GET_SMART VTS2 PGC1
    gap = [0, 0, 0, 3, 0, 0, 0, 0]             # only logical 3 avail -> phys 3
    remap = [0, 2, 1, 0, 0, 0, 0, 0]           # crossed map

    # Directed cases: every semantically distinct arm.
    for log in range(8):
        out.append(vec(0, 1, log, 0b00000111, getsmart))  # map_valid=0 -> identity
        out.append(vec(0, 0, log, 0b00000000, ident))
    out.append(vec(1, 1, 0, 0b00000111, getsmart))        # title hit -> 3
    out.append(vec(1, 1, 2, 0b00000111, getsmart))        # title hit -> 3
    out.append(vec(1, 1, 5, 0b00000111, getsmart))        # title miss -> first (3)
    out.append(vec(1, 1, 0, 0b00001000, gap))             # miss, avail gap -> phys 3
    out.append(vec(1, 1, 1, 0b00000110, remap))           # hit -> 2
    out.append(vec(1, 1, 2, 0b00000110, remap))           # hit -> 1
    out.append(vec(1, 1, 4, 0b00000000, ident))           # all-unavail -> identity 4
    out.append(vec(1, 0, 5, 0b00000111, getsmart))        # menu forces log 0 -> 3
    out.append(vec(1, 0, 5, 0b00000000, ident))           # menu, none avail -> 0
    out.append(vec(1, 0, 0, 0b00000010, remap))           # menu, log0 unavail -> 0

    # Randomized sweep vs the golden model.
    rnd = random.Random(0xD4D)
    for _ in range(2000):
        avail = rnd.getrandbits(8)
        phys = [rnd.getrandbits(3) for _ in range(8)]
        out.append(vec(rnd.getrandbits(1), rnd.getrandbits(1),
                       rnd.getrandbits(3), avail, phys))

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "bench", "dvd", "test_vobs", "aud_map_vec.hex")
    with open(path, "w") as f:
        f.write("// generated by tools/gen_aud_map_vec.py -- do not hand-edit\n")
        for v in out:
            f.write("%010x\n" % v)
    print("wrote %d vectors to %s" % (len(out), os.path.normpath(path)))


if __name__ == "__main__":
    main()
