#!/usr/bin/env python3
"""nav_isa.py -- the navigation sequencer: its instruction set, the assembler,
the ROM image, and the instruction-level emulator (docs/nav_engine.md).

The DVD VM (dvd/dvd_vm.sv) is a microcoded sequencer (dvd/nav/nav_seq.sv) inside a
thin hardwired wrapper. The program, dvd/nav/vm.uasm, is the DVD virtual machine:
command fetch and decode, compare/set/link/jump, the fallback chain, RSM, the
counter-mode tick. The wrapper keeps everything real-time: event latches and their
priority, the wait timer, the output pulses and fields, the SPRM8/SPRM3 shadows,
pre_done, the LFSR. tools/nav_shell.py models that wrapper; this file is the
sequencer. The RTL must match the emulator instruction by instruction.

The method is the audio engine's (tools/dts_isa.py, docs/dts_decoder.md sec 10),
but this is its own small machine: no bit reader, no Huffman walker, no vector ops.
It does not share the audio engine's silicon (docs/logic_reclaim.md sec 10b).

Instruction word, 40 bits (the DTS layout, for familiarity):
    op[39:34] rd[33:30] rs[29:26] rt[25:22] imm[21:6] aux[5:0]
Registers r0..r15 are 16 bits, unsigned; r0 reads 0.

    alu   rd, rs, rt        rd = rs FN rt                  (FN in aux)
    alui  rd, rs, imm       rd = rs FN imm16
    dcmp  rd, rs, rt, rk    rd = the DVD compare (rk & 7) of rs and rt  (rk in aux)
                            0 true, 1 |(a&b), 2 ==, 3 !=, 4 >=, 5 >, 6 <=, 7 <
    ld    rd, imm[rs]       rd = RAM[(rs + imm) & 0xFF]     the data RAM, 256 x 16
    st    rd, imm[rs]       RAM[(rs + imm) & 0xFF] = rd
    ldc   rd, imm[rs]       rd = CMD[(rs + imm) & 0x7FF]    command words, big-endian
    ldp   rd, imm[rs]       rd = PMAP[(rs + imm) & 0x7F]    the program map (bytes)
    in    rd, PORT[rs]      rd = the wrapper's input (aux + rs) & 63
    out   PORT, rs          the wrapper's output aux = rs
    outi  PORT, imm         the wrapper's output aux = imm16
    b<c>  rs, rt, label     branch if rs <c> rt, c in eq ne ltu geu (unsigned)
    b<c>i rs, k, label      ... against an unsigned 10-bit constant k
    bbs / bbc rs, n, label  branch if bit n of rs is set / clear
    jmp / call label, ret   (call stack depth 4)
    jr    rs, label         pc = label + rs (a jump table)
    wev   label, mode       wait for an event, then pc = label + its index
                            (mode 0 = the idle priority set, 1 = the wait set)

Timing: ld, ldc and ldp take 2 cycles, everything else 1; wev waits.

The trace the RTL is scored against (Machine.trace): one tuple (kind, pc, addr,
value) per event, in program order --
    kind 0  a register write    addr = the register, value 16 bits
    kind 1  a store             addr = the RAM address, value 16 bits
    kind 2  an output           addr = the port, value 16 bits
    kind 3  an event dispatch   addr = the mode, value = the index

Usage:
    tools/nav_isa.py --asm [--check]      # assemble dvd/nav/vm.uasm -> dvd/nav/*.mem, .svh
    tools/nav_isa.py --list               # the program with addresses
    tools/nav_isa.py --mutate ARM --mem-out x.mem   # a RED arm's ROM image
    tools/nav_isa.py --mutant ARM DIR     # ... as a runnable dvd_vm.sv (prints its path)
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
NDIR = os.path.join(REPO, 'dvd', 'nav')
UASM = os.path.join(NDIR, 'vm.uasm')
UMEM = os.path.join(NDIR, 'nav_ucode.mem')
USVH = os.path.join(NDIR, 'nav_ucode.svh')
VMSV = os.path.join(REPO, 'dvd', 'dvd_vm.sv')   # its GENERATED blocks
PEEK = os.path.join(REPO, 'bench', 'dvd', 'dvd_vm_peek.svh')
GEN_BEGIN = '// ==== BEGIN GENERATED by tools/nav_isa.py --asm (never edit) ===='
GEN_END = '// ==== END GENERATED ===='

OPS = ['nop', 'alu', 'alui', 'dcmp', 'ld', 'st', 'ldc', 'ldp', 'in', 'out', 'outi',
       'br', 'bri', 'bb', 'jmp', 'call', 'ret', 'jr', 'wev']
OP = {n: i for i, n in enumerate(OPS)}
FNS = ['add', 'sub', 'and', 'or', 'xor', 'shl', 'shr', 'sadd', 'ssub',
       'seq', 'sne', 'sltu', 'sgeu']
FN = {n: i for i, n in enumerate(FNS)}
CONDS = ['eq', 'ne', 'ltu', 'geu']
STACK_DEPTH = 4
UC_DEPTH = 1024                  # 4 M10K at 40 bits (256 x 40 each)
RAM_WORDS = 256
CMD_WORDS = 2048                 # 4096 bytes = 512 commands, the reader's table
PMAP_BYTES = 128

# ------------------------------------------------------------------ the wrapper's ports
# Inputs (in): reader read-backs, cfg, and the wrapper's own state.
IN_PORTS = [
    'CUR_VTS', 'CUR_PGCN', 'CUR_CELL', 'CELL_COUNT', 'NEXT_PGCN', 'PREV_PGCN', 'GOUP_PGCN',
    'NR_PRE', 'NR_POST', 'NR_CELL', 'NR_PGMS', 'AUTO_VTS', 'BEST_MENU_VTS', 'RES_TTN',
    'MENU_ACTIVE', 'CC_NR', 'CHEDGE_DIR', 'LFSR', 'VM_DOM', 'VM_VTS', 'MENU_SEEN',
    'LM_V', 'LM_DOM', 'LM_VTS', 'LM_PGCN', 'JPGCN', 'EVENTS', 'ZERO27',
    'BTN0', 'BTN1', 'BTN2', 'BTN3']
IN = {n: i for i, n in enumerate(IN_PORTS)}
IN['SPRMW'] = 32                 # 32..63: the live-SPRM window (0 for RAM-resident SPRMs)
# Outputs (out / outi). J_DE = {entry[3:0], 2'b0, dom[1:0]} (entry << 4 | dom).
OUT_PORTS = [
    'J_DE', 'J_VTS', 'J_PGCN', 'RSV3', 'J_TTN', 'J_PGN', 'J_PTT', 'J_CELL',
    'SEEK_CELL', 'PULSE', 'BTNF_VAL', 'LF_PGCN', 'SPRM1', 'SPRM2', 'SPRM3', 'SPRM8',
    'VM_DOM', 'VM_VTS', 'FLAGS', 'EVCLR', 'EVSET']
OUT = {n: i for i, n in enumerate(OUT_PORTS)}
# PULSE bits
PULSE_BITS = ['JUMP', 'SEEK', 'REPLAY', 'ADV', 'BTNF', 'LINKFAIL', 'LFSTEP', 'WARM', 'TICKDONE']
PB = {n: 1 << i for i, n in enumerate(PULSE_BITS)}
# FLAGS bits: blk[1:0], nat_src, usr_edge, walk (the tick walk counts as V_IDLE)
FLAG_BITS = {'BLK': 0, 'NAT': 2, 'USR': 3, 'WALK': 4}     # bit positions; blk is 2 bits
# Event latches (EVENTS / EVCLR / EVSET bit order); WEV idle index = bit + 2
EVENTS = ['BOOT', 'ERROR', 'LOADED', 'BTN', 'CELLCMD', 'PGCEND', 'CHEDGE',
          'MENU', 'TITLE', 'CMENU', 'RETURN']
EV = {n: 1 << i for i, n in enumerate(EVENTS)}
# WEV indices
WEV_IDLE = ['TICK', 'DISABLED'] + EVENTS
WEV_WAIT = ['LOADED', 'ERROR', 'TIMEOUT']

# ------------------------------------------------------------------ the data RAM map
# One single-port M10K, touched only by ld/st. Everything the old FSM kept in flops
# that only the VM reads lives here.
RAM_MAP = {
    'GPRM': 0x00,        # 0x00..0x0F the 16 GPRMs
    'GMODE': 0x10,       # counter-mode bits, one per GPRM
    'FB': 0x11,          # the fallback-chain state (FB_*)
    'CVM': 0x12,         # came_via_menukey
    'SKIP_PRE': 0x13,
    'TT_RESOLVE': 0x14,
    'CHAIN': 0x15,       # VM-issued jumps this activation
    'RSM_VTS': 0x18, 'RSM_PGCN': 0x19, 'RSM_CELL': 0x1A,
    'RSM_R4': 0x1B, 'RSM_R5': 0x1C, 'RSM_R6': 0x1D, 'RSM_R7': 0x1E, 'RSM_R8': 0x1F,
    'DE_SEEN': 0x20, 'DE_VTS': 0x21, 'DE_PGCN': 0x22,
    'T0': 0x28,          # 0x28..0x2F handler scratch
    'SPRMI': 0x40,       # 0x40..0x5F the SPRM image: 4..7, 9, 10, 13 live here
}
FB_CODES = {'FB_NONE': 0, 'FB_FP': 1, 'FB_VTSM': 2, 'FB_VTSM2': 3, 'FB_VMGM': 4,
            'FB_TITLE': 5, 'FB_GAVEUP': 6, 'FB_BOOTM': 7}
DOM_CODES = {'DOM_FP': 0, 'DOM_VMGM': 1, 'DOM_VTSM': 2, 'DOM_TT': 3}
BLK_CODES = {'BLK_PRE': 0, 'BLK_POST': 1, 'BLK_CELL': 2, 'BLK_BTN': 3}


def encode(op, rd=0, rs=0, rt=0, imm=0, aux=0):
    return (OP[op] << 34) | ((rd & 15) << 30) | ((rs & 15) << 26) | ((rt & 15) << 22) | \
        ((imm & 0xFFFF) << 6) | (aux & 63)


def decode(w):
    return (OPS[(w >> 34) & 63], (w >> 30) & 15, (w >> 26) & 15, (w >> 22) & 15,
            (w >> 6) & 0xFFFF, w & 63)


def base_equ():
    """The names every program may use: ports, pulse/flag/event bits, the RAM map."""
    equ = {}
    equ.update({'P_' + k: v for k, v in IN.items()})
    equ.update({'O_' + k: v for k, v in OUT.items()})
    equ.update({'PB_' + k: v for k, v in PB.items()})
    equ.update({'F_' + k: 1 << v for k, v in FLAG_BITS.items() if k != 'BLK'})
    equ.update({'FBIT_' + k: v for k, v in FLAG_BITS.items() if k != 'BLK'})
    equ.update({'EV_' + k: v for k, v in EV.items()})
    equ['EV_ALL'] = (1 << len(EVENTS)) - 1
    equ.update({'M_' + k: v for k, v in RAM_MAP.items()})
    equ.update(FB_CODES)
    equ.update(DOM_CODES)
    equ.update(BLK_CODES)
    return equ


# ------------------------------------------------------------------ assembler
class AsmError(Exception):
    pass


def _reg(tok, aliases):
    tok = aliases.get(tok.strip().lower(), tok.strip().lower())
    m = re.fullmatch(r'r(\d+)', tok)
    if not m or int(m.group(1)) > 15:
        raise AsmError(f'not a register: {tok!r}')
    return int(m.group(1))


def _is_reg(tok, aliases):
    tok = aliases.get(tok.strip().lower(), tok.strip().lower())
    return re.fullmatch(r'r\d+', tok) is not None


def assemble(text, mutate=None):
    """-> (words, labels, line numbers). `mutate`: a name; a line carrying
    `;MUT <name>: <instruction>` assembles that instruction instead (the RED arms
    live beside the code they break, as in tools/dts_isa.py)."""
    equ = base_equ()
    aliases, labels, stmts = {}, {}, []
    mutated = False
    for ln, raw in enumerate(text.splitlines(), 1):
        mm = re.search(r';\s*MUT\s+(\w+)\s*:\s*(.*)$', raw)
        line = raw
        if mm and mutate == mm.group(1):
            line = re.sub(r'^(\s*(?:[A-Za-z_][\w.]*:\s*)*).*$', lambda m_: m_.group(1) + mm.group(2), raw)
            mutated = True
        line = re.sub(r';.*', '', line).strip()
        if not line:
            continue
        while True:
            m = re.match(r'([A-Za-z_][\w.]*):\s*(.*)$', line)
            if not m:
                break
            if m.group(1) in labels:
                raise AsmError(f'line {ln}: label {m.group(1)} twice')
            labels[m.group(1)] = len(stmts)
            line = m.group(2).strip()
        if not line:
            continue
        if line.startswith('.equ'):
            _, name, val = line.split(None, 2)
            equ[name] = int(eval(val, {'__builtins__': {}}, dict(equ)))
            continue
        if line.startswith('.reg'):
            _, name, reg = line.split(None, 2)
            aliases[name.lower()] = reg.strip().lower()
            continue
        stmts.append((ln, line, dict(aliases)))
    if mutate and not mutated:
        raise AsmError(f'no MUT {mutate} in the source')
    if len(stmts) > UC_DEPTH:
        raise AsmError(f'{len(stmts)} words exceed the {UC_DEPTH}-word ROM')

    def ev(expr, ln):
        env = dict(equ)
        env.update(labels)
        try:
            return int(eval(expr, {'__builtins__': {}}, env))
        except Exception as e:
            raise AsmError(f'line {ln}: cannot evaluate {expr!r} ({e})')

    words = []
    for ln, line, al in stmts:
        m = re.match(r'(\w+)\s*(.*)$', line)
        mn, rest = m.group(1).lower(), m.group(2)
        args = [a.strip() for a in re.split(r',(?![^\[]*\])', rest)] if rest else []

        def reg(i):
            return _reg(args[i], al)

        def memref(s):
            m2 = re.fullmatch(r'(.*?)\s*\[([^\]]*)\]', s)
            if not m2:
                return ev(s, ln), 0
            imm = ev(m2.group(1), ln) if m2.group(1).strip() else 0
            return imm, (_reg(m2.group(2), al) if m2.group(2).strip() else 0)

        def imm16(v):
            if not -0x8000 <= v <= 0xFFFF:
                raise AsmError(f'line {ln}: constant {v} does not fit 16 bits')
            return v & 0xFFFF

        try:
            if mn in FN:
                if _is_reg(args[2], al):
                    words.append(encode('alu', reg(0), reg(1), reg(2), 0, FN[mn]))
                else:
                    words.append(encode('alui', reg(0), reg(1), 0, imm16(ev(args[2], ln)), FN[mn]))
            elif mn.endswith('i') and mn[:-1] in FN:
                words.append(encode('alui', reg(0), reg(1), 0, imm16(ev(args[2], ln)), FN[mn[:-1]]))
            elif mn == 'li':
                words.append(encode('alui', reg(0), 0, 0, imm16(ev(args[1], ln)), FN['add']))
            elif mn == 'mov':
                words.append(encode('alu', reg(0), reg(1), 0, 0, FN['add']))
            elif mn == 'dcmp':
                words.append(encode('dcmp', reg(0), reg(1), reg(2), 0, reg(3)))
            elif mn in ('ld', 'st', 'ldc', 'ldp'):
                imm, ra = memref(args[1])
                words.append(encode(mn, reg(0), ra, 0, imm16(imm)))
            elif mn == 'in':
                port, ra = memref(args[1])
                if not 0 <= port <= 63:
                    raise AsmError(f'line {ln}: input port {port}')
                words.append(encode('in', reg(0), ra, 0, 0, port))
            elif mn == 'out':
                port = ev(args[0], ln)
                words.append(encode('out', 0, reg(1), 0, 0, port))
            elif mn == 'outi':
                port = ev(args[0], ln)
                words.append(encode('outi', 0, 0, 0, imm16(ev(args[1], ln)), port))
            elif mn[:1] == 'b' and mn[1:] in CONDS:
                words.append(encode('br', CONDS.index(mn[1:]), reg(0), reg(1), ev(args[2], ln)))
            elif mn[:1] == 'b' and mn[1:-1] in CONDS and mn[-1] == 'i':
                c = ev(args[1], ln)
                if not 0 <= c <= 1023:
                    raise AsmError(f'line {ln}: branch constant {c} outside 0..1023')
                words.append(encode('bri', CONDS.index(mn[1:-1]), reg(0), c >> 6,
                                    ev(args[2], ln), c & 63))
            elif mn in ('bbs', 'bbc'):
                n = ev(args[1], ln)
                if not 0 <= n <= 15:
                    raise AsmError(f'line {ln}: bit {n}')
                words.append(encode('bb', 1 if mn == 'bbs' else 0, reg(0), n, ev(args[2], ln)))
            elif mn in ('jmp', 'call'):
                words.append(encode(mn, 0, 0, 0, ev(args[0], ln)))
            elif mn == 'jr':
                words.append(encode('jr', 0, reg(0), 0, ev(args[1], ln)))
            elif mn == 'wev':
                words.append(encode('wev', 0, 0, 0, ev(args[0], ln), ev(args[1], ln)))
            elif mn in ('ret', 'nop'):
                words.append(encode(mn))
            else:
                raise AsmError(f'line {ln}: unknown instruction {mn!r}')
        except (IndexError, KeyError) as e:
            raise AsmError(f'line {ln}: bad operands in {line!r} ({e})')
    for w, (ln, line, _) in zip(words, stmts):
        op, rd, rs, rt, imm, aux = decode(w)
        if op in ('br', 'bri', 'bb', 'jmp', 'call', 'jr', 'wev') and imm >= len(words):
            raise AsmError(f'line {ln}: target {imm} is past the program')
    return words, labels, [ln for ln, _, _ in stmts]


def load_program(mutate=None):
    return assemble(open(UASM).read(), mutate)


# ------------------------------------------------------------------ emulator
class SeqError(Exception):
    pass


def alu(fn, a, b):
    a &= 0xFFFF
    b &= 0xFFFF
    if fn == 0:
        return (a + b) & 0xFFFF
    if fn == 1:
        return (a - b) & 0xFFFF
    if fn == 2:
        return a & b
    if fn == 3:
        return a | b
    if fn == 4:
        return a ^ b
    if fn == 5:
        return (a << (b & 15)) & 0xFFFF
    if fn == 6:
        return a >> (b & 15)
    if fn == 7:
        return min(a + b, 0xFFFF)
    if fn == 8:
        return max(a - b, 0)
    if fn == 9:
        return int(a == b)
    if fn == 10:
        return int(a != b)
    if fn == 11:
        return int(a < b)
    if fn == 12:
        return int(a >= b)
    raise SeqError(f'alu function {fn}')


def dvd_compare(op, a, b):
    """libdvdnav decoder.c eval_compare; op 0 = no compare = true."""
    op &= 7
    return int([True, bool(a & b), a == b, a != b, a >= b, a > b, a <= b, a < b][op])


CYC = {'instr': 1, 'ld': 2}


class Machine:
    """The sequencer. `io` is the wrapper (tools/nav_shell.py Shell): it answers
    in/out, ldc/ldp and wev. run() executes until the program waits at a wev with
    nothing to dispatch."""

    def __init__(self, words, io):
        self.prog = words
        self.io = io
        self.reset()

    def reset(self):
        self.reg = [0] * 16
        self.pc = 0
        self.stack = []
        self.ram = [0] * RAM_WORDS
        self.trace = []
        self.cycles = 0
        self.waiting = None          # the wev mode we are parked at, or None

    def _wr(self, rd, v):
        if rd:
            self.reg[rd] = v & 0xFFFF
            self.trace.append((0, self.pc, rd, v & 0xFFFF))

    def step(self):
        """Execute one instruction. -> False if parked at a wev with nothing to do."""
        w = self.prog[self.pc]
        op, rd, rs, rt, imm, aux = decode(w)
        R = self.reg
        npc = self.pc + 1
        cyc = CYC['instr']
        if op == 'nop':
            pass
        elif op == 'alu':
            self._wr(rd, alu(aux & 15, R[rs], R[rt]))
        elif op == 'alui':
            self._wr(rd, alu(aux & 15, R[rs], imm))
        elif op == 'dcmp':
            self._wr(rd, dvd_compare(R[aux & 15], R[rs], R[rt]))
        elif op == 'ld':
            self._wr(rd, self.ram[(R[rs] + imm) & 0xFF])
            cyc = CYC['ld']
        elif op == 'st':
            a = (R[rs] + imm) & 0xFF
            self.ram[a] = R[rd]
            self.trace.append((1, self.pc, a, R[rd]))
        elif op == 'ldc':
            self._wr(rd, self.io.ldc((R[rs] + imm) & (CMD_WORDS - 1)))
            cyc = CYC['ld']
        elif op == 'ldp':
            self._wr(rd, self.io.ldp((R[rs] + imm) & (PMAP_BYTES - 1)))
            cyc = CYC['ld']
        elif op == 'in':
            self._wr(rd, self.io.inp((aux + R[rs]) & 63))
        elif op in ('out', 'outi'):
            v = R[rs] if op == 'out' else imm
            self.trace.append((2, self.pc, aux, v))
            self.io.out(aux, v)
        elif op in ('br', 'bri', 'bb'):
            a = R[rs]
            if op == 'bb':
                take = bool((a >> rt) & 1) == bool(rd & 1)
            else:
                b = R[rt] if op == 'br' else ((rt << 6) | aux)
                take = [a == b, a != b, a < b, a >= b][rd & 3]
            if take:
                npc = imm
        elif op == 'jmp':
            npc = imm
        elif op == 'call':
            if len(self.stack) >= STACK_DEPTH:
                raise SeqError(f'call stack overflow at pc {self.pc}')
            self.stack.append(self.pc + 1)
            npc = imm
        elif op == 'ret':
            if not self.stack:
                raise SeqError(f'ret with an empty stack at pc {self.pc}')
            npc = self.stack.pop()
        elif op == 'jr':
            npc = (imm + R[rs]) & (UC_DEPTH - 1)
        elif op == 'wev':
            idx = self.io.wev(aux)
            if idx is None:
                self.waiting = aux
                return False
            self.waiting = None
            self.trace.append((3, self.pc, aux, idx))
            npc = imm + idx
        else:
            raise SeqError(f'opcode {op} at pc {self.pc}')
        if npc >= len(self.prog):
            raise SeqError(f'pc {npc} past the program (from {self.pc})')
        self.cycles += cyc
        self.pc = npc
        return True

    def run(self, limit=2_000_000):
        """Run until parked. -> instructions executed."""
        n = 0
        while self.step():
            n += 1
            if n > limit:
                raise SeqError(f'no wev after {limit} instructions (pc {self.pc})')
        return n


# ------------------------------------------------------------------ ROM image
def ucode_svh(words, labels):
    lines = ['// dvd/nav/nav_ucode.svh -- GENERATED by tools/nav_isa.py --asm; never edit.',
             '// The navigation sequencer\'s program size, opcodes, ports, and the data RAM',
             '// map (docs/nav_engine.md). Benches read the RAM through these addresses.',
             f'localparam integer UC_WORDS = {len(words)};',
             f'localparam integer UC_DEPTH = {UC_DEPTH};']
    for n, i in OP.items():
        lines.append(f"localparam [5:0] UOP_{n.upper()} = 6'd{i};")
    for n, i in FN.items():
        lines.append(f"localparam [3:0] UFN_{n.upper()} = 4'd{i};")
    for n, i in IN.items():
        lines.append(f"localparam [5:0] UIN_{n} = 6'd{i};")
    for n, i in OUT.items():
        lines.append(f"localparam [5:0] UOUT_{n} = 6'd{i};")
    for i, n in enumerate(PULSE_BITS):
        lines.append(f'localparam integer UPB_{n} = {i};')
    for n, b in FLAG_BITS.items():
        lines.append(f'localparam integer UFL_{n} = {b};')
    for i, n in enumerate(EVENTS):
        lines.append(f'localparam integer UEV_{n} = {i};')
    lines.append(f'localparam integer UEV_N = {len(EVENTS)};')
    for n, a in RAM_MAP.items():
        lines.append(f"localparam [7:0] UM_{n} = 8'h{a:02x};")
    for n, v in FB_CODES.items():
        lines.append(f"localparam [2:0] U{n} = 3'd{v};")
    return lines


def peek_svh():
    """The benches' view of the VM state that lives in the sequencer's data RAM."""
    M = RAM_MAP
    L = ['// bench/dvd/dvd_vm_peek.svh -- GENERATED by tools/nav_isa.py --asm; never edit.',
         '// The DVD VM\'s state that lives in the sequencer\'s data RAM (docs/nav_engine.md),',
         '// by name, for benches: `include "bench/dvd/dvd_vm_peek.svh", then e.g.',
         '// `VM_GPRM(dut, 3) or `VM_FB(vm) -- reads and writes. Everything else keeps its',
         '// old name on the dvd_vm instance (sprm1/2/3/8, vm_dom, lfsr, wait_tmr, ev_*, ...).',
         '`ifndef DVD_VM_PEEK_SVH', '`define DVD_VM_PEEK_SVH',
         '`define VM_RAM(P, a)    P.u_seq.dram[a]',
         f'`define VM_GPRM(P, i)   P.u_seq.dram[{M["GPRM"]} + (i)]',
         f'`define VM_SPRM(P, n)   P.u_seq.dram[{M["SPRMI"]} + (n)]    // 4..7, 9, 10, 13 only',
         f'`define VM_RSM_R(P, n)  P.u_seq.dram[{M["RSM_R4"]} + (n) - 4]  // n = 4..8']
    for k in ('GMODE', 'FB', 'CVM', 'SKIP_PRE', 'TT_RESOLVE', 'CHAIN', 'RSM_VTS', 'RSM_PGCN',
              'RSM_CELL', 'DE_SEEN', 'DE_VTS', 'DE_PGCN'):
        L.append(f'`define VM_{k}(P){" " * (11 - len(k))}P.u_seq.dram[{M[k]}]')
    L.append('`endif')
    return L


def stamp_rtl(svh):
    """dvd/dvd_vm.sv with every GENERATED block holding the constants. The RTL
    cannot `include the .svh: Icarus does not search the including file's
    directory, so every runner would need -I (docs/nav_engine.md)."""
    text = open(VMSV).read()
    block = GEN_BEGIN + '\n' + '\n'.join(svh[3:]) + '\n' + GEN_END
    pat = re.compile(re.escape(GEN_BEGIN) + r'.*?' + re.escape(GEN_END), re.S)
    n = len(pat.findall(text))
    if n != 2:
        raise AsmError(f'dvd/dvd_vm.sv has {n} GENERATED blocks, expected 2')
    return pat.sub(lambda m: block, text).splitlines()


def write_mems(check=False):
    words, labels, _ = load_program()
    svh = ucode_svh(words, labels)
    files = {UMEM: [f'{w:010x}' for w in words] + ['0000000000'] * (UC_DEPTH - len(words)),
             USVH: svh, VMSV: stamp_rtl(svh), PEEK: peek_svh()}
    bad = []
    for path, lines in files.items():
        text = '\n'.join(lines) + '\n'
        if check:
            if not os.path.exists(path) or open(path).read() != text:
                bad.append(os.path.relpath(path, REPO))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, 'w').write(text)
    print(f'nav_isa: {len(words)} microcode words of {UC_DEPTH}')
    if check:
        print('nav_isa: ' + ('FAIL -- stale: ' + ', '.join(bad) if bad else 'PASS -- generated files match'))
        return 1 if bad else 0
    return 0


def listing():
    words, labels, lines = load_program()
    at = {}
    for n, a in labels.items():
        at.setdefault(a, []).append(n)
    for a, w in enumerate(words):
        for n in at.get(a, []):
            print(f'{n}:')
        op, rd, rs, rt, imm, aux = decode(w)
        print(f'  {a:4d}  {w:010x}  {op:5s} rd={rd} rs={rs} rt={rt} imm={imm} aux={aux}'
              f'   ; line {lines[a]}')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--asm', action='store_true', help='assemble and write the ROM files')
    ap.add_argument('--check', action='store_true', help='with --asm: compare, do not write')
    ap.add_argument('--list', action='store_true', help='print the assembled program')
    ap.add_argument('--mutate', help='assemble with this ;MUT arm (with --mem-out)')
    ap.add_argument('--mutant', nargs=2, metavar=('ARM', 'DIR'),
                    help='write DIR/dvd_vm_ARM.sv: the RTL running the ;MUT arm ARM')
    ap.add_argument('--mem-out', help='write only the ROM image here (a RED arm\'s ROM: a '
                    'runner points a copy of dvd/dvd_vm.sv at it)')
    a = ap.parse_args()
    if a.mutant:
        # a RED arm as a runnable RTL: DIR/<arm>.mem and DIR/dvd_vm_<arm>.sv, a copy of
        # dvd/dvd_vm.sv whose ROM loads that image. Prints the .sv path.
        os.makedirs(a.mutant[1], exist_ok=True)
        mem = os.path.abspath(os.path.join(a.mutant[1], a.mutant[0] + '.mem'))
        words, _, _ = load_program(a.mutant[0])
        open(mem, 'w').write('\n'.join([f'{w:010x}' for w in words] +
                                       ['0000000000'] * (UC_DEPTH - len(words))) + '\n')
        sv = os.path.join(a.mutant[1], f'dvd_vm_{a.mutant[0]}.sv')
        text = open(VMSV).read()
        assert text.count('"dvd/nav/nav_ucode.mem"') == 1
        open(sv, 'w').write(text.replace('"dvd/nav/nav_ucode.mem"', f'"{mem}"'))
        print(sv)
        return 0
    if a.mem_out:
        words, _, _ = load_program(a.mutate)
        open(a.mem_out, 'w').write('\n'.join([f'{w:010x}' for w in words] +
                                              ['0000000000'] * (UC_DEPTH - len(words))) + '\n')
        return 0
    if a.list:
        listing()
        return 0
    if a.asm:
        return write_mems(a.check)
    ap.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
