// ============================================================================
// dvd/transport_hud.sv -- Phase 11: transport HUD (graphic on-screen status)
// ============================================================================
// Release-visible playback feedback, rendered in fabric and composited through
// the existing subpic_blend register stage in emu.sv (NOT the `ifdef
// DEBUG_OVERLAY block overlay, which is compiled out of release builds).
//
// Status line (bottom-anchored, 32 cells of 16x32 px = 512 px wide):
//   [icon] H:MM:SS/H:MM:SS CH n/N
// shown while: the Display button's persistent mode is ON, paused, a scrub
// gesture is held (bar_active), or for ~2.5 s after a transport event
// (show_evt re-arms the timer). Hidden while a disc menu is up (the HLI
// highlight layer owns the screen there); persistent mode survives and the
// line reappears on resume.
//
// ARCHITECTURE (the display-hotspot rule, see docs/roadmap.md "Phase 11"):
// all string/format work happens at EVENT RATE in a small formatter FSM that
// writes glyph indices into a 32-cell text-plane RAM; the DISPLAY path is a
// 4-stage registered pixel pipeline that is a pure function of (h_pos, v_pos)
//   A: region hit-test + cell/glyph coordinate split (registered)
//   B: text-plane sync read (glyph index for the cell)
//   C: glyph-ROM sync read (one 8-px 2-bpp row)
//   D: pixel-class -> colour/alpha resolve (registered output)
// The (x,y)-purity makes it inherently CRT-480i safe (v_pos is the absolute
// frame line in field mode, same contract as the subtitle/HLI hit-tests).
// The 4-clk latency is absorbed by the HUD_QX_ADJ column lead (the SP_QX_ADJ
// precedent -- HW-calibrated).
//
// Glyph ROM: 64 glyphs x 16 rows x 8 px x 2 bpp (one M10K), generated by
// tools/hud_font.py -> dvd/hud_font.mem. Pixel classes: 0 transparent,
// 1 outline (black), 2 fill (white / accent). Class-0 pixels of an ACTIVE
// cell (glyph != GLYPH_NONE) render as a translucent dark BACKING so the
// text reads over any video.
//
// Current time is CELL-relative (dsi_c_eltm) until the step-6 whole-title
// prefix-sum lands; total time = pgc_playback_time. Both are BCD dvd_time --
// digits map straight to glyph indices, no binary conversion.
// ============================================================================

module transport_hud #(
    parameter HUD_QX_ADJ = 4,               // pipeline latency lead (raster px)
    parameter SHOW_TICKS = 27'd67_500_000   // ~2.5 s @ 27 MHz
)(
    input  wire        clk,                 // clk_sys (dot clock domain)
    input  wire        rst_n,

    // raster position (core output raster, absolute frame coords)
    input  wire [11:0] h_pos,
    input  wire [11:0] v_pos,
    input  wire        pal_mode,            // 1 = 576-line active region

    // visibility state / events
    input  wire        menu_active,         // suppress the HUD in menus
    input  wire        dbg_mode,            // DIAGNOSTIC (O[2]): force the status line
                                            // always-visible (even in menus) and always
                                            // show the CH field - emu repurposes cur_pgm/
                                            // nr_pgm as {reader PGCN, VTS} so the boot/
                                            // how-to-play PGC path is readable on-screen.
    input  wire        pause_q,             // manual pause (keeps the line up)
    input  wire        bar_active,          // scrub gesture held + linger
    input  wire        scrub_held,          // D-pad held (FF/REW icon while 1)
    input  wire        scrub_dir,           // 1 = forward
    input  wire [1:0]  scrub_tier,          // speed tier 0..3 -> x1..x4
    input  wire        display_edge,        // B9: toggle persistent mode
    input  wire        load_evt,            // fresh media load: clear + hide
    input  wire        show_evt,            // transport event: re-arm show_tmr

    // values (BCD dvd_time {hh,mm,ss,ff}; chapter numbers binary, <= 99)
    input  wire [31:0] cur_time,
    input  wire [31:0] total_time,
    input  wire [7:0]  cur_pgm,             // 0 = unresolved -> CH hidden
    input  wire [7:0]  nr_pgm,              // 0 = no chapters -> CH hidden

    // popup events (last one wins the single popup slot) + their values.
    // The popup row re-renders every formatter pass from LIVE values, so a
    // value that settles a few cycles after its event (e.g. the reader's
    // attr-BRAM language read) self-heals on the next ~1.2 ms refresh.
    input  wire        aud_evt,             // audio-track cycle (B7)
    input  wire        sub_evt,             // subtitle cycle (B8)
    input  wire        angle_evt,           // angle cycle (B6)
    input  wire        chap_evt,            // chapter skip (B2/B3)
    // CSS warning: LEVEL input (emu's sticky per-mount latch). While high the
    // popup shows "CSS ENCRYPTED" persistently — user events (audio/sub/angle/
    // chapter) take the slot for their 2.5 s, then the warning re-arms. Unlike
    // every other popup it is NOT hidden in menus (a scrambled disc's menu is
    // exactly where the user is staring at green garbage).
    input  wire        css_warn,
    // Phase-2 failure messaging (docs/roadmap.md "Public alpha release prep").
    // Both are LEVELS, arbitrated below css_warn, and both are menu-exempt for
    // the same reason CSS is: a silent or blank menu is exactly where the user
    // is staring when these fire.
    input  wire        img_warn,            // unplayable image (flat-file path, no video)
    input  wire        aud_warn,            // selected audio track is an unsupported format
    // Title-VTS notice: a PULSE at mount, only raised on the largest-VTS
    // heuristic path (Disc Menus Off) where a wrong pick is actually possible.
    input  wire        vts_evt,
    input  wire [7:0]  vts_no,
    input  wire [3:0]  aud_no,              // 1-based playing audio track
    input  wire [3:0]  aud_cnt,
    input  wire [15:0] aud_lang,            // 2-ASCII ISO-639 (0 = none)
    input  wire        sub_enabled,
    input  wire [3:0]  sub_no,              // 1-based subtitle track
    input  wire [3:0]  sub_cnt,
    input  wire [15:0] sub_lang,
    input  wire [3:0]  ang_no,              // 1-based angle
    input  wire [3:0]  ang_cnt,

    // pixel out, REGISTERED (feed emu's pre-blend register stage)
    output reg         hud_on,
    output reg  [7:0]  hud_r,
    output reg  [7:0]  hud_g,
    output reg  [7:0]  hud_b,
    output reg  [3:0]  hud_alpha
);

    // ---- glyph indices (keep in sync with tools/hud_font.py) --------------
    localparam [5:0] G_COLON = 6'd10, G_SLASH = 6'd11, G_SPACE = 6'd14,
                     G_X     = 6'd15, G_A     = 6'd16,
                     G_PLAY  = 6'd42, G_PAUSE = 6'd43, G_REV = 6'd44,
                     G_NONE  = 6'd63;
    localparam [5:0] G_C = G_A + 6'd2, G_H = G_A + 6'd7;

    // ---- layout ------------------------------------------------------------
    localparam [11:0] X0    = 12'd104;      // (720 - 32*16)/2
    localparam [11:0] ROW_H = 12'd32;       // 16 glyph rows at 2x
    // status row bottom-anchored; the popup row sits above it with a gap that
    // clears the seek bar (activeH-78..-69, dvd/seek_bar.sv):
    //   popup  activeH-112 .. -81
    //   bar    activeH-78  .. -69
    //   status activeH-64  .. -33
    wire [11:0] act_h = (pal_mode ? 12'd576 : 12'd480);
    wire [11:0] y0    = act_h - 12'd64;     // status row top
    wire [11:0] y0p   = act_h - 12'd112;    // popup row top

    // ---- visibility --------------------------------------------------------
    reg        persist_q;
    reg [26:0] show_tmr;
    reg [26:0] pop_tmr;
    reg [2:0]  pop_type;                    // 0 aud, 1 sub, 2 angle, 3 chapter, 4 CSS
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            persist_q <= 1'b0;
            show_tmr  <= 27'd0;
            pop_tmr   <= 27'd0;
            pop_type  <= 3'd0;
        end else begin
            if (display_edge) persist_q <= ~persist_q;
            if (load_evt)     persist_q <= 1'b0;
            if (show_evt || display_edge) show_tmr <= SHOW_TICKS;
            else if (load_evt)            show_tmr <= 27'd0;
            else if (show_tmr != 27'd0)   show_tmr <= show_tmr - 27'd1;
            // popup: last event wins the single slot
            if (aud_evt)        begin pop_type <= 3'd0; pop_tmr <= SHOW_TICKS; end
            else if (sub_evt)   begin pop_type <= 3'd1; pop_tmr <= SHOW_TICKS; end
            else if (angle_evt) begin pop_type <= 3'd2; pop_tmr <= SHOW_TICKS; end
            else if (chap_evt)  begin pop_type <= 3'd3; pop_tmr <= SHOW_TICKS; end
            else if (vts_evt)   begin pop_type <= 3'd7; pop_tmr <= SHOW_TICKS; end
            else if (load_evt)          pop_tmr <= 27'd0;
            // CSS warning: lowest priority so user popups show for their 2.5 s,
            // then the warning re-takes the slot for as long as css_warn holds.
            // Warnings, in ROOT-CAUSE order: CSS explains a muted/green disc, an
            // unplayable image explains everything downstream of it, and the
            // audio-format notice is the narrowest. Each re-takes the slot for as
            // long as its level holds.
            // ⚠ PREEMPTION (HW round 1, 2026-08-23): a higher-priority warning must
            // be able to take the slot from a LOWER-priority warning that is already
            // showing, not just wait for a free one. These levels do not assert
            // simultaneously — aud_warn arms at nav_ready (IFO parsed) while
            // css_scrambled needs 4 scrambled PES, i.e. a moment of actual stream —
            // so on a scrambled disc the narrower notice won the slot first and held
            // it for its full 2.5 s before CSS could speak. Preemption is scoped to
            // warnings only: user events (types 0-3) are never preempted, so the
            // "user popup wins the slot" contract is unchanged.
            else if (css_warn && (pop_tmr == 27'd0 ||
                                  pop_type == 3'd5 || pop_type == 3'd6))
                                begin pop_type <= 3'd4; pop_tmr <= SHOW_TICKS; end
            else if (img_warn && (pop_tmr == 27'd0 || pop_type == 3'd6))
                                begin pop_type <= 3'd5; pop_tmr <= SHOW_TICKS; end
            else if (aud_warn && pop_tmr == 27'd0)
                                begin pop_type <= 3'd6; pop_tmr <= SHOW_TICKS; end
            else if (pop_tmr != 27'd0)  pop_tmr <= pop_tmr - 27'd1;
        end
    end
    wire vis = dbg_mode ? 1'b1                       // diagnostic: always on, incl. menus
             : (persist_q | pause_q | bar_active | (show_tmr != 27'd0)) && !menu_active;
    // CSS warning shows in menus too (scrambled discs green-screen there first)
    wire pop_vis = (pop_tmr != 27'd0) &&
                   (!menu_active || pop_type == 3'd4 ||
                    pop_type == 3'd5 || pop_type == 3'd6);

    // ---- text plane (2 rows x 32 cells x {accent, glyph[5:0]}) -------------
    reg [6:0] plane [0:63];                 // addr = {row, col}
    reg [6:0] tp_q;

    // ---- glyph ROM (M10K): {glyph[5:0], row[3:0]} -> 8 px x 2 bpp ----------
    reg [15:0] font_rom [0:1023];
    initial $readmemh("dvd/hud_font.mem", font_rom);
    reg [15:0] rom_q;

    // =========================================================================
    // Formatter (event-rate): refresh the whole line every ~1.2 ms from a
    // snapshot latched at the start of each pass (no mid-string tearing).
    // One plane write per cycle; digits are BCD nibbles -> glyph indices.
    // =========================================================================
    function [7:0] bin2bcd99(input [7:0] v);   // {tens[3:0], ones[3:0]}, v <= 99
        reg [3:0] t;
        reg [7:0] rem;
        begin
            t = (v >= 8'd90) ? 4'd9 : (v >= 8'd80) ? 4'd8 :
                (v >= 8'd70) ? 4'd7 : (v >= 8'd60) ? 4'd6 :
                (v >= 8'd50) ? 4'd5 : (v >= 8'd40) ? 4'd4 :
                (v >= 8'd30) ? 4'd3 : (v >= 8'd20) ? 4'd2 :
                (v >= 8'd10) ? 4'd1 : 4'd0;
            rem = v - {1'b0, t, 3'b000} - {3'b000, t, 1'b0};   // v - t*8 - t*2
            bin2bcd99 = {t, rem[3:0]};
        end
    endfunction

    // ASCII -> glyph (letters only; anything else = NONE, i.e. don't render)
    function [5:0] a2g(input [7:0] c);
        begin
            if (c >= "A" && c <= "Z")      a2g = G_A + {1'b0, c[4:0]} - 6'd1;
            else if (c >= "a" && c <= "z") a2g = G_A + {1'b0, c[4:0]} - 6'd1;
            else                           a2g = G_NONE;
        end
    endfunction

    // format snapshot (status row)
    reg [23:0] f_cur, f_tot;                 // {h,mm,ss} BCD (hh ones digit kept)
    reg [7:0]  f_n, f_nn;                    // CH n / N as {tens,ones} BCD
    reg        f_ch;                         // show the CH section
    reg [1:0]  f_icon;                       // 0 play, 1 pause, 2 ffwd, 3 rev
    reg [3:0]  f_tier1;                      // tier+1 (1..4)
    // format snapshot (popup row)
    reg [2:0]  f2_type;
    reg [7:0]  f2_n, f2_nn;                  // n / N as {tens,ones} BCD
    reg [5:0]  f2_l1, f2_l2;                 // language glyphs (NONE = hidden)
    reg        f2_off;                       // SUB OFF variant

    reg [6:0]  fmt_col;                      // 0..63 write cursor, 64+ = idle
    reg [14:0] fmt_wait;

    // glyph for one text-plane cell, from the snapshots. fmt_col[5] selects the
    // row: 0 = status line, 1 = popup line.
    reg [6:0] fmt_g;
    reg [5:0] pop_lbl;                       // popup label glyph for cols 0..4
    always @(*) begin
        pop_lbl = G_SPACE;
        case (fmt_col[4:0])
            5'd0: case (f2_type)
                2'd0: pop_lbl = G_A;                    // A
                2'd1: pop_lbl = G_A + 6'd18;            // S
                2'd2: pop_lbl = G_A;                    // A
                2'd3: pop_lbl = G_C;                    // C
            endcase
            5'd1: case (f2_type)
                2'd0: pop_lbl = G_A + 6'd20;            // U
                2'd1: pop_lbl = G_A + 6'd20;            // U
                2'd2: pop_lbl = G_A + 6'd13;            // N
                2'd3: pop_lbl = G_H;                    // H
            endcase
            5'd2: case (f2_type)
                2'd0: pop_lbl = G_A + 6'd3;             // D
                2'd1: pop_lbl = G_A + 6'd1;             // B
                2'd2: pop_lbl = G_A + 6'd6;             // G
                2'd3: pop_lbl = G_SPACE;
            endcase
            5'd3: case (f2_type)
                2'd0: pop_lbl = G_A + 6'd8;             // I
                2'd2: pop_lbl = G_A + 6'd11;            // L
                default: pop_lbl = G_SPACE;
            endcase
            5'd4: case (f2_type)
                2'd0: pop_lbl = G_A + 6'd14;            // O
                2'd2: pop_lbl = G_A + 6'd4;             // E
                default: pop_lbl = G_SPACE;
            endcase
            default: pop_lbl = G_SPACE;
        endcase

        fmt_g = {1'b0, G_SPACE};
        if (fmt_col[5] && f2_type == 3'd4) begin
            // ---- popup row, CSS warning: "CSS ENCRYPTED" (accent), cols 0-12 --
            case (fmt_col[4:0])
                5'd0:  fmt_g = {1'b1, a2g("C")};
                5'd1:  fmt_g = {1'b1, a2g("S")};
                5'd2:  fmt_g = {1'b1, a2g("S")};
                5'd3:  fmt_g = {1'b0, G_SPACE};
                5'd4:  fmt_g = {1'b1, a2g("E")};
                5'd5:  fmt_g = {1'b1, a2g("N")};
                5'd6:  fmt_g = {1'b1, a2g("C")};
                5'd7:  fmt_g = {1'b1, a2g("R")};
                5'd8:  fmt_g = {1'b1, a2g("Y")};
                5'd9:  fmt_g = {1'b1, a2g("P")};
                5'd10: fmt_g = {1'b1, a2g("T")};
                5'd11: fmt_g = {1'b1, a2g("E")};
                5'd12: fmt_g = {1'b1, a2g("D")};
                default: fmt_g = {1'b0, G_NONE};
            endcase
        end else if (fmt_col[5] && f2_type == 3'd5) begin
            // ---- popup row: unplayable image (accent), cols 0-16 -----------
            case (fmt_col[4:0])
                5'd0:  fmt_g = {1'b1, a2g("U")};
                5'd1:  fmt_g = {1'b1, a2g("N")};
                5'd2:  fmt_g = {1'b1, a2g("S")};
                5'd3:  fmt_g = {1'b1, a2g("U")};
                5'd4:  fmt_g = {1'b1, a2g("P")};
                5'd5:  fmt_g = {1'b1, a2g("P")};
                5'd6:  fmt_g = {1'b1, a2g("O")};
                5'd7:  fmt_g = {1'b1, a2g("R")};
                5'd8:  fmt_g = {1'b1, a2g("T")};
                5'd9:  fmt_g = {1'b1, a2g("E")};
                5'd10: fmt_g = {1'b1, a2g("D")};
                5'd11: fmt_g = {1'b0, G_SPACE};
                5'd12: fmt_g = {1'b1, a2g("I")};
                5'd13: fmt_g = {1'b1, a2g("M")};
                5'd14: fmt_g = {1'b1, a2g("A")};
                5'd15: fmt_g = {1'b1, a2g("G")};
                5'd16: fmt_g = {1'b1, a2g("E")};
                default: fmt_g = {1'b0, G_NONE};
            endcase
        end else if (fmt_col[5] && f2_type == 3'd6) begin
            // ---- popup row: unsupported audio format (accent), cols 0-16 ---
            case (fmt_col[4:0])
                5'd0:  fmt_g = {1'b1, a2g("A")};
                5'd1:  fmt_g = {1'b1, a2g("U")};
                5'd2:  fmt_g = {1'b1, a2g("D")};
                5'd3:  fmt_g = {1'b1, a2g("I")};
                5'd4:  fmt_g = {1'b1, a2g("O")};
                5'd5:  fmt_g = {1'b0, G_SPACE};
                5'd6:  fmt_g = {1'b1, a2g("U")};
                5'd7:  fmt_g = {1'b1, a2g("N")};
                5'd8:  fmt_g = {1'b1, a2g("S")};
                5'd9:  fmt_g = {1'b1, a2g("U")};
                5'd10: fmt_g = {1'b1, a2g("P")};
                5'd11: fmt_g = {1'b1, a2g("P")};
                5'd12: fmt_g = {1'b1, a2g("O")};
                5'd13: fmt_g = {1'b1, a2g("R")};
                5'd14: fmt_g = {1'b1, a2g("T")};
                5'd15: fmt_g = {1'b1, a2g("E")};
                5'd16: fmt_g = {1'b1, a2g("D")};
                default: fmt_g = {1'b0, G_NONE};
            endcase
        end else if (fmt_col[5] && f2_type == 3'd7) begin
            // ---- popup row: "TITLE VTS nn" (cols 0-8 label, 10-11 digits) --
            case (fmt_col[4:0])
                5'd0:  fmt_g = {1'b1, a2g("T")};
                5'd1:  fmt_g = {1'b1, a2g("I")};
                5'd2:  fmt_g = {1'b1, a2g("T")};
                5'd3:  fmt_g = {1'b1, a2g("L")};
                5'd4:  fmt_g = {1'b1, a2g("E")};
                5'd5:  fmt_g = {1'b0, G_SPACE};
                5'd6:  fmt_g = {1'b1, a2g("V")};
                5'd7:  fmt_g = {1'b1, a2g("T")};
                5'd8:  fmt_g = {1'b1, a2g("S")};
                5'd9:  fmt_g = {1'b0, G_SPACE};      // gap before the digits
                5'd10: fmt_g = {1'b0, 2'b00, f2_n[7:4]};
                5'd11: fmt_g = {1'b0, 2'b00, f2_n[3:0]};
                default: fmt_g = {1'b0, G_NONE};
            endcase
        end else if (fmt_col[5]) begin
            // ---- popup row: [label 0-4] sp [n/N 6-10] sp [lang 12-13] ------
            case (fmt_col[4:0])
                5'd0, 5'd1, 5'd2, 5'd3, 5'd4: fmt_g = {1'b1, pop_lbl};  // accent
                5'd5:  fmt_g = {1'b0, G_SPACE};
                5'd6:  fmt_g = f2_off ? {1'b0, G_A + 6'd14}                  // O
                             : (f2_n[7:4] != 4'd0) ? {1'b0, 2'b00, f2_n[7:4]}
                                                   : {1'b0, G_SPACE};
                5'd7:  fmt_g = f2_off ? {1'b0, G_A + 6'd5}                   // F
                                      : {1'b0, 2'b00, f2_n[3:0]};
                5'd8:  fmt_g = f2_off ? {1'b0, G_A + 6'd5}                   // F
                                      : {1'b0, G_SLASH};
                5'd9:  fmt_g = f2_off ? {1'b0, G_NONE}
                             : (f2_nn[7:4] != 4'd0) ? {1'b0, 2'b00, f2_nn[7:4]}
                                                    : {1'b0, G_SPACE};
                5'd10: fmt_g = f2_off ? {1'b0, G_NONE} : {1'b0, 2'b00, f2_nn[3:0]};
                5'd11: fmt_g = (f2_l1 != G_NONE) ? {1'b0, G_SPACE} : {1'b0, G_NONE};
                5'd12: fmt_g = {1'b0, f2_l1};
                5'd13: fmt_g = {1'b0, f2_l2};
                default: fmt_g = {1'b0, G_NONE};
            endcase
        end else
        case (fmt_col[4:0])
            5'd0:  fmt_g = (f_icon == 2'd1) ? {1'b0, G_PAUSE} :
                           (f_icon == 2'd3) ? {1'b1, G_REV}   :
                           (f_icon == 2'd2) ? {1'b1, G_PLAY}  : {1'b0, G_PLAY};
            5'd1:  fmt_g = (f_icon == 2'd2) ? {1'b1, G_PLAY} :
                           (f_icon == 2'd3) ? {1'b1, G_REV}  : {1'b0, G_SPACE};
            5'd2:  fmt_g = (f_icon[1]) ? {1'b1, G_X} : {1'b0, G_SPACE};
            5'd3:  fmt_g = (f_icon[1]) ? {1'b1, {2'b00, f_tier1}} : {1'b0, G_SPACE};
            5'd5:  fmt_g = {1'b0, 2'b00, f_cur[23:20]};    // h
            5'd6:  fmt_g = {1'b0, G_COLON};
            5'd7:  fmt_g = {1'b0, 2'b00, f_cur[19:16]};    // m tens
            5'd8:  fmt_g = {1'b0, 2'b00, f_cur[15:12]};    // m ones
            5'd9:  fmt_g = {1'b0, G_COLON};
            5'd10: fmt_g = {1'b0, 2'b00, f_cur[11:8]};     // s tens
            5'd11: fmt_g = {1'b0, 2'b00, f_cur[7:4]};      // s ones
            5'd12: fmt_g = {1'b0, G_SLASH};
            5'd13: fmt_g = {1'b0, 2'b00, f_tot[23:20]};
            5'd14: fmt_g = {1'b0, G_COLON};
            5'd15: fmt_g = {1'b0, 2'b00, f_tot[19:16]};
            5'd16: fmt_g = {1'b0, 2'b00, f_tot[15:12]};
            5'd17: fmt_g = {1'b0, G_COLON};
            5'd18: fmt_g = {1'b0, 2'b00, f_tot[11:8]};
            5'd19: fmt_g = {1'b0, 2'b00, f_tot[7:4]};
            5'd21: fmt_g = f_ch ? {1'b0, G_C} : {1'b0, G_SPACE};
            5'd22: fmt_g = f_ch ? {1'b0, G_H} : {1'b0, G_SPACE};
            5'd24: fmt_g = (f_ch && f_n[7:4] != 4'd0) ? {1'b0, 2'b00, f_n[7:4]}
                                                      : {1'b0, G_SPACE};
            5'd25: fmt_g = f_ch ? {1'b0, 2'b00, f_n[3:0]} : {1'b0, G_SPACE};
            5'd26: fmt_g = f_ch ? {1'b0, G_SLASH} : {1'b0, G_SPACE};
            5'd27: fmt_g = (f_ch && f_nn[7:4] != 4'd0) ? {1'b0, 2'b00, f_nn[7:4]}
                                                       : {1'b0, G_SPACE};
            5'd28: fmt_g = f_ch ? {1'b0, 2'b00, f_nn[3:0]} : {1'b0, G_SPACE};
            5'd29, 5'd30, 5'd31: fmt_g = {1'b0, G_NONE};   // no backing tail
            default: fmt_g = {1'b0, G_SPACE};
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            fmt_col  <= 7'd65;
            fmt_wait <= 15'd0;
            f_cur <= 24'd0; f_tot <= 24'd0; f_n <= 8'd0; f_nn <= 8'd0;
            f_ch <= 1'b0; f_icon <= 2'd0; f_tier1 <= 4'd1;
            f2_type <= 3'd0; f2_n <= 8'd0; f2_nn <= 8'd0;
            f2_l1 <= G_NONE; f2_l2 <= G_NONE; f2_off <= 1'b0;
        end else begin
            if (fmt_col <= 7'd63) begin
                plane[fmt_col[5:0]] <= fmt_g;
                fmt_col <= fmt_col + 7'd1;
            end else if (fmt_wait != 15'd0) begin
                fmt_wait <= fmt_wait - 15'd1;
            end else begin
                // snapshot, then rewrite both rows
                f_cur   <= {cur_time[27:8],   4'd0};   // {h ones, mm, ss} nibbles
                f_tot   <= {total_time[27:8], 4'd0};
                f_n     <= bin2bcd99(cur_pgm);
                f_nn    <= bin2bcd99(nr_pgm);
                f_ch    <= dbg_mode ? 1'b1 : (cur_pgm != 8'd0) && (nr_pgm != 8'd0);
                f_icon  <= scrub_held ? (scrub_dir ? 2'd2 : 2'd3)
                                      : (pause_q ? 2'd1 : 2'd0);
                f_tier1 <= {2'b00, scrub_tier} + 4'd1;
                f2_type <= pop_type;
                f2_off  <= 1'b0;
                f2_l1   <= G_NONE;
                f2_l2   <= G_NONE;
                if (pop_type == 3'd7) f2_n <= bin2bcd99(vts_no);
                case (pop_type)
                    2'd0: begin
                        f2_n  <= bin2bcd99({4'd0, aud_no});
                        f2_nn <= bin2bcd99({4'd0, aud_cnt});
                        f2_l1 <= a2g(aud_lang[15:8]);
                        f2_l2 <= a2g(aud_lang[7:0]);
                    end
                    2'd1: begin
                        f2_n  <= bin2bcd99({4'd0, sub_no});
                        f2_nn <= bin2bcd99({4'd0, sub_cnt});
                        f2_off <= !sub_enabled;
                        if (sub_enabled) begin
                            f2_l1 <= a2g(sub_lang[15:8]);
                            f2_l2 <= a2g(sub_lang[7:0]);
                        end
                    end
                    2'd2: begin
                        f2_n  <= bin2bcd99({4'd0, ang_no});
                        f2_nn <= bin2bcd99({4'd0, ang_cnt});
                    end
                    2'd3: begin
                        f2_n  <= bin2bcd99(cur_pgm);
                        f2_nn <= bin2bcd99(nr_pgm);
                    end
                endcase
                fmt_col  <= 7'd0;
                fmt_wait <= 15'h7FFF;           // ~1.2 ms between passes
            end
        end
    end

    // =========================================================================
    // Pixel pipeline (display path): pure function of (h_pos, v_pos).
    // =========================================================================
    wire [11:0] hx  = h_pos + HUD_QX_ADJ[11:0] - X0;
    wire        inx = (h_pos + HUD_QX_ADJ[11:0] >= X0) &&
                      (h_pos + HUD_QX_ADJ[11:0] <  X0 + 12'd512);
    wire [11:0] vy_s = v_pos - y0;          // status row
    wire        in_s = vis && (v_pos >= y0)  && (v_pos < y0  + ROW_H);
    wire [11:0] vy_p = v_pos - y0p;         // popup row
    wire        in_p = pop_vis && (v_pos >= y0p) && (v_pos < y0p + ROW_H);

    // A: hit-test + coordinate split
    reg       s0_in;
    reg       s0_row;                       // 0 = status, 1 = popup
    reg [4:0] s0_col;
    reg [2:0] s0_gx;
    reg [3:0] s0_gy;
    // B: text-plane read
    reg       s1_in;
    reg [2:0] s1_gx;
    reg [3:0] s1_gy;
    // C: ROM read
    reg       s2_in, s2_act, s2_acc;
    reg [2:0] s2_gx;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s0_in <= 1'b0; s0_row <= 1'b0; s0_col <= 5'd0; s0_gx <= 3'd0; s0_gy <= 4'd0;
            s1_in <= 1'b0; s1_gx <= 3'd0; s1_gy <= 4'd0; tp_q <= 7'd0;
            s2_in <= 1'b0; s2_act <= 1'b0; s2_acc <= 1'b0; s2_gx <= 3'd0;
            rom_q <= 16'd0;
            hud_on <= 1'b0; hud_r <= 8'd0; hud_g <= 8'd0; hud_b <= 8'd0;
            hud_alpha <= 4'd0;
        end else begin
            // A
            s0_in  <= (in_s || in_p) && inx;
            s0_row <= in_p;
            s0_col <= hx[8:4];
            s0_gx  <= hx[3:1];
            s0_gy  <= in_p ? vy_p[4:1] : vy_s[4:1];
            // B
            tp_q  <= plane[{s0_row, s0_col}];
            s1_in <= s0_in;
            s1_gx <= s0_gx;
            s1_gy <= s0_gy;
            // C
            rom_q  <= font_rom[{tp_q[5:0], s1_gy}];
            s2_in  <= s1_in;
            s2_act <= (tp_q[5:0] != G_NONE);
            s2_acc <= tp_q[6];
            s2_gx  <= s1_gx;
            // D: pixel class -> colour/alpha
            hud_on    <= 1'b0;
            hud_r     <= 8'd0; hud_g <= 8'd0; hud_b <= 8'd0;
            hud_alpha <= 4'd0;
            if (s2_in) begin
                case (rom_q[{~s2_gx, 1'b0} +: 2])  // MSB pair = leftmost: k = 7-gx = ~gx
                    2'd2: begin                     // fill: white / accent amber
                        hud_on <= 1'b1; hud_alpha <= 4'd15;
                        hud_r  <= 8'hFF;
                        hud_g  <= s2_acc ? 8'hC8 : 8'hFF;
                        hud_b  <= s2_acc ? 8'h20 : 8'hFF;
                    end
                    2'd1: begin                     // outline: opaque black
                        hud_on <= 1'b1; hud_alpha <= 4'd15;
                    end
                    default: if (s2_act) begin      // backing: translucent black
                        hud_on <= 1'b1; hud_alpha <= 4'd6;
                    end
                endcase
            end
        end
    end

endmodule
