// aud_stream_map_tb.sv - bit-exact check of dvd/aud_stream_map.sv against the
// golden model tools/dvd_vm_ref.py aud_stream_map() (the libdvdnav
// vm_get_audio_stream / vm_get_audio_active_stream port, with the documented
// identity deviation).
//
// Vectors: bench/dvd/test_vobs/aud_map_vec.hex, generated by
// tools/gen_aud_map_vec.py (directed cases for every arm - map_valid=0
// identity, menu force-0, title hit, title miss -> first available,
// all-unavailable identity, the GET_SMART VTS2 shape - plus a 2000-vector
// seeded random sweep). Regenerate with:  python3 tools/gen_aud_map_vec.py

`timescale 1ns/1ps

module aud_stream_map_tb;

    localparam NVEC = 2026;               // directed + random (see generator)

    reg  [39:0] vec [0:NVEC-1];

    reg         map_valid, dom_tt;
    reg  [2:0]  logical;
    reg  [7:0]  avail;
    reg  [23:0] phys_flat;
    wire [2:0]  phys_streamN;

    aud_stream_map dut (
        .map_valid    (map_valid),
        .dom_tt       (dom_tt),
        .logical      (logical),
        .avail        (avail),
        .phys_flat    (phys_flat),
        .phys_streamN (phys_streamN)
    );

    integer i, errors = 0, n = 0;
    reg [2:0] expect_v;
    initial begin
        $readmemh("bench/dvd/test_vobs/aud_map_vec.hex", vec);
        for (i = 0; i < NVEC; i = i + 1) begin
            if (^vec[i] === 1'bx) begin
                // short file guard: stop at the first unloaded entry
                i = NVEC;
            end else begin
                {expect_v, phys_flat, avail, logical, dom_tt, map_valid} = vec[i];
                #1;
                if (phys_streamN !== expect_v) begin
                    errors = errors + 1;
                    $display("FAIL vec %0d: mv=%b tt=%b log=%0d avail=%08b flat=%06x -> %0d (expect %0d)",
                             i, map_valid, dom_tt, logical, avail, phys_flat,
                             phys_streamN, expect_v);
                end
                n = n + 1;
            end
        end
        if (n < 100) begin
            errors = errors + 1;
            $display("FAIL: only %0d vectors loaded (fixture missing?)", n);
        end
        if (errors == 0) $display("AUD_STREAM_MAP_TB: ALL %0d VECTORS PASSED", n);
        else begin $display("AUD_STREAM_MAP_TB: %0d FAILURE(S)", errors); $fatal(1); end
        $finish;
    end

endmodule
