#!/usr/bin/env bash
#
# csync_extract.sh — pull the REAL framework pieces out of sys/sys_top.v for the
# composite-sync benches. Sourced by run_csync_field.sh, run_csync_sweep.sh and
# run_csync_pipe.sh so all three test the shipped code, never a copy that can drift.
#
# Two things are extracted:
#   1. `module csync` -> bench/dvd/csync_ref_gen.v as `csync_ref`. sys_top.v cannot be
#      compiled standalone (VHDL neighbours, includes), so the module is lifted out.
#      One mechanical edit on the way: iverilog rejects the module's use-before-declare
#      (`assign csync = ...` above `reg csync_hs, csync_vs;`), so the reg line is hoisted
#      above the assign. Logic untouched.
#   2. `localparam integer CS_PIPE = N;` -> bench/dvd/csync_pipe_gen.vh. That constant
#      is how many clocks sys_top delays the core's VGA_CS to line it up with the
#      framework's own hsync latency; csync_pipe_tb.sv MEASURES the latency through the
#      real scanlines/osd/csync and fails if the two disagree.
#
# ★ csync_ref is also CHECKSUMMED (csync_sha). The "Stock" arm of csync_field_tb.sv
# claims the pre-change behaviour is bit-identical, and it can only claim that about the
# module it was given — so an edit to `module csync` must fail the run rather than
# silently redefine what "stock" means. Two earlier attempts DID edit that module (2H
# serrations; synthesising the half-line from VGA_F1) and both were reverted.
# To adopt a deliberate change, run with CSYNC_SHA_UPDATE=1 and commit the new value.

CSYNC_REF_SHA_EXPECT=""   # set below from bench/dvd/csync_ref.sha256

csync_extract() {
  local root="$1"
  local gen="$root/bench/dvd/csync_ref_gen.v"
  local vh="$root/bench/dvd/csync_pipe_gen.vh"
  local shafile="$root/bench/dvd/csync_ref.sha256"

  {
    echo "// GENERATED by bench/dvd/csync_extract.sh from sys/sys_top.v — do not edit"
    awk '/^module csync$/,/^endmodule/' "$root/sys/sys_top.v" \
      | sed 's/^module csync$/module csync_ref/' \
      | awk '
          /^reg csync_hs, csync_vs;/ { next }                       # drop from original spot
          /^assign csync = / { print "reg csync_hs, csync_vs;"; }   # hoist above the assign
          { print }'
  } > "$gen"
  grep -q "reg csync_hs, csync_vs;" "$gen" || { echo "csync extraction failed"; return 1; }

  # -- G2: the stock module must be the one these benches were written against -------
  local sha
  sha=$(sed '1d' "$gen" | sha256sum | cut -d' ' -f1)
  if [ "${CSYNC_SHA_UPDATE:-0}" = "1" ]; then
    echo "$sha" > "$shafile"
    echo "csync_extract: PINNED sys_top.v module csync -> $sha"
  elif [ -f "$shafile" ]; then
    local want
    want=$(tr -d '[:space:]' < "$shafile")
    if [ "$sha" != "$want" ]; then
      echo "FAIL: sys/sys_top.v \`module csync\` has changed."
      echo "      expected $want"
      echo "      found    $sha"
      echo "      The 'Stock' arm of csync_field_tb.sv asserts the pre-change analog sync is"
      echo "      bit-identical to THIS module. Leaving it stock is also what keeps the"
      echo "      DVD-fork note above it true. If the change is deliberate, re-run with"
      echo "      CSYNC_SHA_UPDATE=1 and commit bench/dvd/csync_ref.sha256."
      return 1
    fi
  else
    echo "csync_extract: no bench/dvd/csync_ref.sha256 — run once with CSYNC_SHA_UPDATE=1"
    return 1
  fi

  # -- sys_top's CS_PIPE, for csync_pipe_tb ------------------------------------------
  local pipe
  pipe=$(grep -oE '^localparam integer CS_PIPE = [0-9]+;' "$root/sys/sys_top.v" \
         | grep -oE '[0-9]+' | head -1)
  [ -n "$pipe" ] || { echo "CS_PIPE not found in sys/sys_top.v"; return 1; }
  {
    echo "// GENERATED by bench/dvd/csync_extract.sh from sys/sys_top.v — do not edit"
    echo "\`define CS_PIPE_EXPECT $pipe"
  } > "$vh"
  return 0
}
