// subp_stream_map_tb.sv - bit-exact check of dvd/subp_stream_map.sv against the
// golden model tools/dvd_vm_ref.py subp_stream_map() (the libdvdnav
// vm_get_subp_stream port, with this core's documented forced-wide-for-menus
// deviation and the identity fallback).
//
// Vectors: bench/dvd/test_vobs/subp_map_vec.hex, generated by
// tools/gen_subp_map_vec.py. The directed cases are the REAL disc census, not
// invented numbers -- 0x80010200 is what BOTH issue #60/#61 discs author on
// every menu PGC, and 0x80000100 is what 16 of the 17 non-identity library
// discs author (the arm that must NOT change). Regenerate with:
//     python3 tools/gen_subp_map_vec.py
//
// Packed vector, LSB first:
//   [0] map_valid  [1] dom_tt  [2] ctx_menu  [3] wide
//   [5:4] disp_mode  [9:6] logical  [41:10] ctl_sel  [46:42] expect

`timescale 1ns/1ps

module subp_stream_map_tb;

    localparam NVEC = 2071;               // directed + random (see generator)

    reg  [47:0] vec [0:NVEC-1];

    reg         map_valid, dom_tt, ctx_menu, wide;
    reg  [1:0]  disp_mode;
    reg  [3:0]  logical;
    reg  [31:0] ctl_sel;
    wire [4:0]  phys_streamN;

    subp_stream_map dut (
        .map_valid    (map_valid),
        .dom_tt       (dom_tt),
        .ctx_menu     (ctx_menu),
        .logical      (logical),
        .ctl_sel      (ctl_sel),
        .wide         (wide),
        .disp_mode    (disp_mode),
        .phys_streamN (phys_streamN)
    );

    integer i, errors = 0, n = 0;
    integer n_menu_fix = 0;      // menu arms that resolve to a NON-ZERO substream
    reg [4:0] expect_v;
    reg [1:0] unused_hi;
    initial begin
        $readmemh("bench/dvd/test_vobs/subp_map_vec.hex", vec);
        for (i = 0; i < NVEC; i = i + 1) begin
            if (^vec[i] === 1'bx) begin
                i = NVEC;                       // short-file guard
            end else begin
                {unused_hi, expect_v, ctl_sel, logical, disp_mode,
                 wide, ctx_menu, dom_tt, map_valid} = vec[i];
                #1;
                if (phys_streamN !== expect_v) begin
                    errors = errors + 1;
                    if (errors < 20)
                        $display("FAIL vec %0d: mv=%b tt=%b menu=%b wide=%b dm=%0d log=%0d ctl=%08x -> %0d (expect %0d)",
                                 i, map_valid, dom_tt, ctx_menu, wide, disp_mode,
                                 logical, ctl_sel, phys_streamN, expect_v);
                end
                if (ctx_menu && !dom_tt && map_valid && phys_streamN != 5'd0)
                    n_menu_fix = n_menu_fix + 1;
                n = n + 1;
            end
        end
        if (n < 100) begin
            errors = errors + 1;
            $display("FAIL: only %0d vectors loaded (fixture missing?)", n);
        end
        // The suite must actually EXERCISE the fix: if no menu vector ever
        // resolves to a non-zero substream then every arm agrees with the old
        // hardcoded 0 and this bench cannot fail for the reason it exists.
        if (n_menu_fix < 5) begin
            errors = errors + 1;
            $display("FAIL: only %0d menu vectors resolve to a NON-ZERO substream --", n_menu_fix);
            $display("      the vectors do not exercise issues #60/#61 at all");
        end
        if (errors == 0)
            $display("SUBP_STREAM_MAP_TB: ALL %0d VECTORS PASSED (%0d menu arms map to a non-zero substream)",
                     n, n_menu_fix);
        else begin
            $display("SUBP_STREAM_MAP_TB: %0d FAILURE(S) over %0d vectors", errors, n);
            $fatal(1);
        end
        $finish;
    end
endmodule
