// subp_stream_map_tb.sv - bit-exact check of dvd/subp_stream_map.sv against the
// golden model tools/dvd_vm_ref.py subp_stream_map() (the libdvdnav
// vm_get_subp_stream port, with this core's documented forced-wide-for-menus
// deviation and the identity fallback).
//
// Vectors: bench/dvd/test_vobs/subp_map_vec.hex, generated by
// tools/gen_subp_map_vec.py. The directed cases are the REAL disc census, not
// invented numbers -- 0x80010200 is what BOTH issue #60/#61 discs author on
// every menu PGC, and 0x80000100 is what 16 of the 17 non-identity library
// discs author (the arm that must NOT change). Regenerate with:
//     python3 tools/gen_subp_map_vec.py
//
// Packed vector, LSB first:
//   [0] map_valid  [1] dom_tt  [2] menu_dom  [3] wide
//   [5:4] disp_mode  [9:6] logical  [41:10] ctl_sel  [46:42] expect

`timescale 1ns/1ps

module subp_stream_map_tb;

    localparam NVEC = 2077;               // directed + random (see generator)

    reg  [47:0] vec [0:NVEC-1];

    reg         map_valid, dom_tt, menu_dom, wide;
    reg  [1:0]  disp_mode;
    reg  [3:0]  logical;
    reg  [31:0] ctl_sel;
    wire [4:0]  phys_streamN;
    wire        stream_absent;
    reg         any_present = 1'b0;

    subp_stream_map dut (
        .map_valid    (map_valid),
        .dom_tt       (dom_tt),
        .menu_dom     (menu_dom),
        .logical      (logical),
        .ctl_sel      (ctl_sel),
        .wide         (wide),
        .disp_mode    (disp_mode),
        .any_present  (any_present),
        .phys_streamN (phys_streamN),
        .stream_absent(stream_absent)
    );

    integer i, errors = 0, n = 0;
    integer n_menu_fix = 0;      // menu arms that resolve to a NON-ZERO substream
    reg [4:0] expect_v;
    reg [1:0] unused_hi;
    initial begin
        $readmemh("bench/dvd/test_vobs/subp_map_vec.hex", vec);
        for (i = 0; i < NVEC; i = i + 1) begin
            if (^vec[i] === 1'bx) begin
                i = NVEC;                       // short-file guard
            end else begin
                {unused_hi, expect_v, ctl_sel, logical, disp_mode,
                 wide, menu_dom, dom_tt, map_valid} = vec[i];
                #1;
                if (phys_streamN !== expect_v) begin
                    errors = errors + 1;
                    if (errors < 20)
                        $display("FAIL vec %0d: mv=%b tt=%b mdom=%b wide=%b dm=%0d log=%0d ctl=%08x -> %0d (expect %0d)",
                                 i, map_valid, dom_tt, menu_dom, wide, disp_mode,
                                 logical, ctl_sel, phys_streamN, expect_v);
                end
                if (menu_dom && !dom_tt && map_valid && phys_streamN != 5'd0)
                    n_menu_fix = n_menu_fix + 1;
                n = n + 1;
            end
        end
        if (n < 100) begin
            errors = errors + 1;
            $display("FAIL: only %0d vectors loaded (fixture missing?)", n);
        end
        // The suite must actually EXERCISE the fix: if no menu vector ever
        // resolves to a non-zero substream then every arm agrees with the old
        // hardcoded 0 and this bench cannot fail for the reason it exists.
        if (n_menu_fix < 5) begin
            errors = errors + 1;
            $display("FAIL: only %0d menu vectors resolve to a NON-ZERO substream --", n_menu_fix);
            $display("      the vectors do not exercise issues #60/#61 at all");
        end
        // ---- STREAM AVAILABILITY (the white-rabbit subtitle case) ------------
        // The 2071 packed vectors above pin phys_streamN, which this output does not
        // touch; they run with any_present=0 and are unaffected. These directed arms
        // pin stream_absent, using the REAL disc words: The Matrix VTS_02 PGCN 6
        // declares logical 1 only (0x80020300), so a user asking for logical 0 -- an
        // entry that reads all-zero -- must be told the stream is absent rather than
        // being shown 0x20 under a palette that renders every subtitle class as one
        // flat grey.
        begin : avail_arms
            map_valid = 1; dom_tt = 1; menu_dom = 0; wide = 1; disp_mode = 0;

            // [1] class C: the table declares SOMETHING, but not this entry -> absent
            any_present = 1; logical = 4'd0; ctl_sel = 32'h00000000; #1;
            if (stream_absent !== 1'b1) begin
                errors = errors + 1;
                $display("FAIL [avail-1]: undeclared entry in a PGC that declares others must be ABSENT");
            end

            // [2] the SAME entry when the PGC declares NOTHING (class B, 586 PGCs in
            //     the library sweep) -> NOT absent; the identity fallback must stand,
            //     or those discs silently lose their subtitles.
            any_present = 0; logical = 4'd0; ctl_sel = 32'h00000000; #1;
            if (stream_absent !== 1'b0) begin
                errors = errors + 1;
                $display("FAIL [avail-2]: a PGC that declares NO stream must keep the identity fallback");
            end

            // [3] a declared entry is never absent (the normal case, 18,801 PGCs)
            any_present = 1; logical = 4'd0; ctl_sel = 32'h80000100; #1;
            if (stream_absent !== 1'b0) begin
                errors = errors + 1;
                $display("FAIL [avail-3]: a DECLARED stream must not be reported absent");
            end

            // [4] the rabbit's own stream stays selectable (logical 1, 0x80020300)
            any_present = 1; logical = 4'd1; ctl_sel = 32'h80020300; #1;
            if (stream_absent !== 1'b0 || phys_streamN !== 5'd2) begin
                errors = errors + 1;
                $display("FAIL [avail-4]: the rabbit's declared stream must resolve to 0x22 and not be absent (abs=%b phys=%0d)",
                         stream_absent, phys_streamN);
            end

            // [5] no usable table at all -> never absent, whatever any_present says
            map_valid = 0; any_present = 1; logical = 4'd0; ctl_sel = 32'h00000000; #1;
            if (stream_absent !== 1'b0) begin
                errors = errors + 1;
                $display("FAIL [avail-5]: an unparsed table must not report absence");
            end
            map_valid = 1;

            // [6] wrong domain (a MENU-DOMAIN player against a title table) -> not absent
            menu_dom = 1; any_present = 1; logical = 4'd0; ctl_sel = 32'h00000000; #1;
            if (stream_absent !== 1'b0) begin
                errors = errors + 1;
                $display("FAIL [avail-6]: an out-of-domain table must not report absence");
            end
            menu_dom = 0;

            if (errors == 0) $display("  stream_absent: 6 directed arms PASS (class C absent, class B preserved)");
        end

        // ---- ISSUE #81: AN IN-TITLE MENU IS A MENU CONTEXT IN THE TITLE DOMAIN --
        // A DVD-game / motion-menu disc authors its menus as TITLE-domain PGCs with
        // the button HLI in the NAV packs (Scene It's game menus; Aniki mon Frere /
        // BROTHER PAL FR R2, the reported disc). emu calls that a menu context
        // (sp_menu_early -> menu_sp_ctx) and resolves LOGICAL stream 0 -- but the
        // loaded table is the TITLE's, and the player is in the TITLE domain.
        //
        // ⚠ THE MODULE'S TRUTH TABLE DID NOT CHANGE for this fix: the old
        // `ctx_menu ? ~dom_tt : dom_tt` is the same function of (dom_tt, bit 2) as
        // `dom_tt != menu_dom`. What changed is WHICH FACT emu puts on that bit --
        // the domain the player is in, not whether the caller wanted a menu. So
        // these arms pin the CONTRACT, and the thing that can actually regress is
        // the wiring: gated separately by tools/check_subp_map_wiring.py, which
        // reads the port connection out of dvd/emu.sv and is RED on the pre-#81 file.
        begin : in_title_menu_arms
            map_valid = 1; any_present = 1; wide = 1; disp_mode = 0; logical = 4'd0;

            // [7] the reported disc's word, in the title domain -> 0x21, not 0x20.
            dom_tt = 1; menu_dom = 0; ctl_sel = 32'h80010200; #1;
            if (phys_streamN !== 5'd1 || stream_absent !== 1'b0) begin
                errors = errors + 1;
                $display("FAIL [81-1]: in-title menu must resolve logical 0 -> physical 1 (got %0d abs=%b)",
                         phys_streamN, stream_absent);
            end

            // [8] the PRE-FIX WIRING, reproduced: emu passed the menu CONTEXT (1)
            //     while the player was in the title domain, so the gate rejected the
            //     title's table and fell back to identity -> 0x20 -> nothing for the
            //     highlight to recolour -> "no visible selection". This arm both
            //     documents the defect and proves the gate still fires on a GENUINE
            //     domain mismatch (a menu-domain player reading a title table).
            dom_tt = 1; menu_dom = 1; ctl_sel = 32'h80010200; #1;
            if (phys_streamN !== 5'd0) begin
                errors = errors + 1;
                $display("FAIL [81-2]: a genuine domain mismatch must still fall back to identity (got %0d)",
                         phys_streamN);
            end

            // [9] a 4:3 in-title menu takes the >>24 field, like every other 4:3 path
            dom_tt = 1; menu_dom = 0; wide = 0; ctl_sel = 32'h80010200; #1;
            if (phys_streamN !== 5'd0) begin
                errors = errors + 1;
                $display("FAIL [81-3]: 4:3 in-title menu must take the 4:3 field (got %0d)", phys_streamN);
            end
            wide = 1;

            // [10] the 16-of-17 library word must NOT move in the title domain: its
            //      wide field is 0, so every disc that works today is unchanged.
            dom_tt = 1; menu_dom = 0; ctl_sel = 32'h80000100; #1;
            if (phys_streamN !== 5'd0) begin
                errors = errors + 1;
                $display("FAIL [81-4]: the common library word must still resolve to 0 in wide mode (got %0d)",
                         phys_streamN);
            end

            if (errors == 0) $display("  issue #81: 4 directed in-title-menu arms PASS (logical 0 -> 0x21)");
        end

        if (errors == 0)
            $display("SUBP_STREAM_MAP_TB: ALL %0d VECTORS PASSED (%0d menu arms map to a non-zero substream)",
                     n, n_menu_fix);
        else begin
            $display("SUBP_STREAM_MAP_TB: %0d FAILURE(S) over %0d vectors", errors, n);
            $fatal(1);
        end
        $finish;
    end
endmodule
