// vcd_chain_tb.sv — full-chain VCD test: a REAL deblocked VCD slice (MPEG-1
// system stream, MP2 44.1 kHz audio on stream_id 0xC0) through the pipeline
//     ps_demux -> ac3_reframer -> dts_reframer -> mp2_reframer -> audio_ring
//     -> dvd_audio_decode (mp2_decode inside)
// with the PCM output compared BIT-EXACT against tools/mp2_ref.py's decode of
// the same audio ES, plus the 44.1 kHz NCO rate checks:
//   [1] once MP2 sync is up, dvd_audio_decode.nco_fs selects 44.1 kHz (2'd0)
//   [2] the sample tick cadence measures 44100 Hz +/-1% (27 MHz clk model)
//   [3] in +SCHED mode (real drain gate) nco_fs never changes while draining
//       (the glitch-free swap contract)
//
// Fixtures: bench/dvd/test_vobs/vcd_mid.golden.hex (committed, real PAL VCD);
// PCM golden generated by bench/dvd/run_vcd.sh into
// bench/dvd/test_mp2/vcdchain/ (gitignored, regenerable).
//
// Run: bench/dvd/run_vcd.sh   (or see its iverilog line; +SCHED for gate mode)

`timescale 1ns/1ps
`default_nettype none

module vcd_chain_tb;

    logic clk = 0;
    always #5 clk = ~clk;
    logic rst_n = 0;

    // ---- deblocked VCD feed -> ps_demux ----
    localparam int MAXB = 1 << 18;
    logic [7:0] vob [0:MAXB-1];
    int nbytes, fed = 0;

    // Registered prefetch feed (combinational vob[fed] reads elaborate a huge
    // mux in iverilog — the mp2_chain_tb lesson).
    logic [7:0] in_byte;
    wire        in_ready;
    logic       prefetched = 0;
    wire        in_valid = prefetched && rst_n && (fed < nbytes);
    always @(posedge clk) begin
        if (!rst_n) begin
            fed <= 0; prefetched <= 0;
        end else if (!prefetched) begin
            in_byte <= vob[0]; prefetched <= 1;
        end else if (in_valid && in_ready) begin
            in_byte <= vob[fed + 1];
            fed     <= fed + 1;
        end
    end

    wire [7:0]  ps_aud_byte;
    wire        ps_aud_valid, ps_aud_ready;
    wire [1:0]  ps_aud_type;
    wire        ps_aud_frame_start;
    wire [32:0] ps_aud_frame_pts;
    wire        ps_aud_frame_pts_valid;

    ps_demux demux (
        .clk(clk), .rst_n(rst_n),
        .in_byte(in_byte), .in_valid(in_valid), .in_ready(in_ready),
        .aud_track(3'd0),
        .sp_track(3'd0), .sp_enable(1'b0),
        .vid_byte(), .vid_valid(), .vid_ready(1'b1),
        .aud_byte(ps_aud_byte), .aud_valid(ps_aud_valid), .aud_type(ps_aud_type),
        .aud_frame_start(ps_aud_frame_start), .aud_ready(ps_aud_ready),
        .vid_pts(), .vid_pts_valid(), .aud_pts(), .aud_pts_valid(),
        .aud_frame_pts(ps_aud_frame_pts), .aud_frame_pts_valid(ps_aud_frame_pts_valid),
        .sp_byte(), .sp_valid(), .sp_frame_start(), .sp_pts(), .sp_pts_valid(),
        .pci_enable(1'b0), .pci_byte(), .pci_valid(), .pci_frame_start(),
        .dsi_enable(1'b0), .dsi_byte(), .dsi_valid(), .dsi_frame_start(),
        .aud_lpcm_quant(), .pes_scrambled()
    );

    wire ps_aud_xfer = ps_aud_valid && ps_aud_ready;

    // ---- reframer chain (identical wiring to emu.sv) ----
    wire [7:0]  ar_b;  wire ar_v;  wire [1:0] ar_t;  wire ar_s;
    wire [32:0] ar_p;  wire ar_pv;
    ac3_reframer u_ar (
        .clk(clk), .rst_n(rst_n),
        .in_byte(ps_aud_byte), .in_valid(ps_aud_xfer), .in_type(ps_aud_type),
        .in_frame_start(ps_aud_frame_start),
        .in_frame_pts(ps_aud_frame_pts), .in_frame_pts_valid(ps_aud_frame_pts_valid),
        .out_byte(ar_b), .out_valid(ar_v), .out_type(ar_t),
        .out_frame_start(ar_s), .out_frame_pts(ar_p), .out_frame_pts_valid(ar_pv)
    );
    wire [7:0]  dr_b;  wire dr_v;  wire [1:0] dr_t;  wire dr_s;
    wire [32:0] dr_p;  wire dr_pv;
    dts_reframer u_dr (
        .clk(clk), .rst_n(rst_n),
        .in_byte(ar_b), .in_valid(ar_v), .in_type(ar_t), .in_frame_start(ar_s),
        .in_frame_pts(ar_p), .in_frame_pts_valid(ar_pv),
        .out_byte(dr_b), .out_valid(dr_v), .out_type(dr_t),
        .out_frame_start(dr_s), .out_frame_pts(dr_p), .out_frame_pts_valid(dr_pv)
    );
    wire [7:0]  rf_b;  wire rf_v;  wire [1:0] rf_t;  wire rf_s;
    wire [32:0] rf_p;  wire rf_pv;
    mp2_reframer u_mr (
        .clk(clk), .rst_n(rst_n),
        .in_byte(dr_b), .in_valid(dr_v), .in_type(dr_t), .in_frame_start(dr_s),
        .in_frame_pts(dr_p), .in_frame_pts_valid(dr_pv),
        .out_byte(rf_b), .out_valid(rf_v), .out_type(rf_t),
        .out_frame_start(rf_s), .out_frame_pts(rf_p), .out_frame_pts_valid(rf_pv)
    );

    // ---- audio_ring ----
    wire [7:0]  ring_byte;
    wire        ring_valid, ring_ready;
    wire        frame_valid, frame_pop;
    wire [15:0] frame_len;
    wire [1:0]  frame_type;
    wire [32:0] frame_pts;
    wire        frame_pts_valid;
    wire        ring_almost_full;

    audio_ring #(.BYTE_DEPTH(32768), .FRAME_DEPTH(128)) u_ring (
        .clk(clk), .rst_n(rst_n),
        .aud_byte(rf_b), .aud_valid(rf_v), .aud_type(rf_t),
        .aud_frame_start(rf_s),
        .aud_frame_pts(rf_p), .aud_frame_pts_valid(rf_pv),
        .aud_ready(),
        .almost_full(ring_almost_full),
        .drop_pulse(1'b0),
        .out_byte(ring_byte), .out_valid(ring_valid), .out_ready(ring_ready),
        .frame_valid(frame_valid), .frame_len(frame_len), .frame_type(frame_type),
        .frame_pts(frame_pts), .frame_pts_valid(frame_pts_valid),
        .frame_pop(frame_pop),
        .frames_available(), .bytes_available(), .overflow_count()
    );
    assign ps_aud_ready = ~ring_almost_full;

    // ---- STC model (only advances in +SCHED mode): 90 kHz from 27 MHz ----
    logic        sched_mode = 0;
    logic [32:0] stc_r = 33'd0;
    logic        stc_init = 0;
    logic [8:0]  stc_div = 0;
    always @(posedge clk) begin
        if (sched_mode && rst_n && stc_init) begin
            stc_div <= (stc_div == 9'd299) ? 9'd0 : stc_div + 9'd1;
            if (stc_div == 9'd299) stc_r <= stc_r + 33'd1;
        end
    end

    wire signed [15:0] audio_l, audio_r;

    dvd_audio_decode dut (
        .clk(clk), .rst_n(rst_n),
        .enable(1'b1),
        .pause(1'b0),
        .ring_byte(ring_byte), .ring_valid(ring_valid), .ring_ready(ring_ready),
        .frame_valid(frame_valid), .frame_len(frame_len), .frame_type(frame_type),
        .lpcm_quant(2'd0),
        .frame_pts(frame_pts), .frame_pts_valid(frame_pts_valid),
        .frame_pop(frame_pop),
        .nco_trim(22'sd0),
        .dispatch_pts(), .dispatch_pts_valid(),
        .sched_en(sched_mode),
        .stc_anchored(sched_mode),
        .arr_pts(33'd0), .arr_pts_valid(1'b0),
        .video_live(sched_mode),
        .stc(stc_r),
        .av_ofs(18'sd0),
        .audio_l(audio_l), .audio_r(audio_r),
        .ac3_synced(), .ac3_err(),
        .dbg_ac3_resets(), .dbg_ac3_err_resets(),
        .dbg_draining(), .dbg_play_pts_valid(), .dbg_armed_data(),
        .dbg_skip_run(), .dbg_play_pts(),
        .dbg_rearm_cnt(), .dbg_fbrel_cnt(), .dbg_skip_cnt(), .dbg_play_err()
    );

    // ---- PCM capture (mp2 core aud_valid -> output latch, next cycle) ----
    wire mp2_avalid = dut.mp2_aud_valid;
    logic mp2_avalid_d;
    always @(posedge clk) mp2_avalid_d <= mp2_avalid;

    localparam int MAXS = 1 << 16;
    logic [31:0] golden [0:MAXS-1];
    int nsamp;
    int got = 0, errs = 0;

    always @(posedge clk) begin
        if (mp2_avalid_d) begin
            if (got < nsamp && {audio_r, audio_l} !== golden[got]) begin
                if (errs < 10)
                    $display("MISMATCH s%0d: dut {r,l}=%04x%04x golden=%08x",
                             got, audio_r & 16'hffff, audio_l & 16'hffff, golden[got]);
                errs++;
            end
            got++;
        end
    end

    // ---- [1]+[3] NCO rate-select checks ----
    logic [1:0] nco_fs_d = 2'd1;
    int fs_glitch = 0;
    always @(posedge clk) if (rst_n) begin
        nco_fs_d <= dut.nco_fs;
        if (dut.draining && (dut.nco_fs !== nco_fs_d)) begin
            fs_glitch++;
            $display("ERR: nco_fs changed while draining (t=%0t)", $time);
        end
    end

    // ---- [2] sample-tick cadence: count aud_ce over a 27 MHz-cycle window ----
    int ce_cnt = 0, win_cnt = 0;
    logic meas_en = 0;
    always @(posedge clk) if (meas_en) begin
        win_cnt++;
        if (dut.aud_ce) ce_cnt++;
    end

    // ---- audio PES PTS fixture (for the +SCHED STC preroll) ----
    logic [39:0] apts [0:255];

    initial begin
        if ($test$plusargs("SCHED")) sched_mode = 1;
        $readmemh("bench/dvd/test_vobs/vcd_mid.golden.hex", vob);
        $readmemh("bench/dvd/test_mp2/vcdchain/pcm_golden.hex", golden);
        $readmemh("bench/dvd/test_vobs/vcd_mid.apts.hex", apts);
        nbytes = 0;
        while (nbytes < MAXB && !$isunknown(vob[nbytes])) nbytes++;
        nsamp = 0;
        while (nsamp < MAXS && !$isunknown(golden[nsamp])) nsamp++;
        if (nbytes == 0 || nsamp == 0)
            $fatal(1, "fixtures missing (run bench/dvd/run_vcd.sh)");
        // STC preroll: ~33 ms below the first audio PES PTS
        stc_r = apts[0][32:0] - 33'd3000;
        stc_init = 1;
        $display("chain fixture: %0d PS bytes, %0d golden samples, sched=%0d",
                 nbytes, nsamp, sched_mode);

        repeat (8) @(posedge clk);
        rst_n = 1;

        // start the cadence window once the rate select has settled to 44.1
        wait (dut.nco_fs == 2'd0);
        repeat (1000) @(posedge clk);
        meas_en = 1;

        wait (got >= nsamp);
        meas_en = 0;
        repeat (100) @(posedge clk);

        if (dut.nco_fs !== 2'd0) begin
            $display("ERR: nco_fs=%0d, expected 44.1 kHz (0)", dut.nco_fs);
            errs++;
        end
        // cadence: ticks/window vs 44100/27e6 (+/-1%)
        begin : cadence
            longint expect_ticks;
            expect_ticks = (longint'(win_cnt) * 44100) / 27000000;
            $display("cadence: %0d ticks in %0d cycles (expect ~%0d)",
                     ce_cnt, win_cnt, expect_ticks);
            if (ce_cnt < (expect_ticks * 99) / 100 ||
                ce_cnt > (expect_ticks * 101) / 100) begin
                $display("ERR: sample-tick cadence outside +/-1%% of 44100");
                errs++;
            end
        end
        if (fs_glitch != 0) errs++;

        if (errs == 0) begin
            $display("PASS: vcd_chain_tb — %0d samples BIT-EXACT, 44.1 kHz NCO verified%0s",
                     got, sched_mode ? " (sched gate mode)" : "");
            $finish;
        end else begin
            $display("RESULT: %0d error(s)", errs);
            $fatal(1, "vcd_chain_tb failed");
        end
    end

    initial begin
        #600000000000;   // 600 ms sim time
        $fatal(1, "vcd_chain_tb TIMEOUT");
    end

endmodule
`default_nettype wire
